### ISSUE TITLE
Fix translations on timeago

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/democracyos#1039]
We are currently showing labels like `Cierra in 5 days`

**Comment by slifszyc** [comment]
Related: https://github.com/moment/moment/issues/2007

**Comment by jfresco** [comment]
We can implement in `democracyos-timeago` the workaround described on https://github.com/moment/moment/issues/2007#issue-46628834.
It's ugly, but we can keep the uglyness encapsulated.

**Comment by slifszyc** [comment]
There has been some improvement on https://github.com/moment/moment so I'll be checking this out these days
