### ISSUE TITLE
There's no way to close the calendar

### ISSUE THREAD

**Issue by ebrenman** [DemocracyOS/democracyos#1066]
If you decide not to set a date for a topic, there's no way to close the calendar dialog.

<img width="307" alt="screen shot 2015-10-03 at 12 31 52 pm" src="https://cloud.githubusercontent.com/assets/2765706/10263606/c7125182-69ca-11e5-9690-f708c0382893.png">

https://asamblea.partidodelared.org/admin/topics/create?publish=true&short=true

**Comment by ben-pr-p** [comment]
This is a problem here – @slifszyc https://github.com/slifszyc/datepicker/blob/master/index.js

```
Datepicker.prototype.onclick = function(e){
  if (this.popover) return;
  this.cal.once('change', bind(this, this.onchange));
  this.popover = new Popover(this.cal.el);
  this.popover.classname = 'datepicker-popover popover';
  this.popover.show(this.el);
};
``` 
should include a check to see if it's already open, in which case it closes it.

I'll do it!
