### ISSUE TITLE
[notifications] - Update notifier calls

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/democracyos#1073]
`Notifier.notify` calls should change: now we should use the `Notification` model to create a new `notification` object on the db.

**Comment by jfresco** [comment]
Done on https://github.com/DemocracyOS/democracyos/commit/441de8ef25bf6751058c1b092a70729ad778f58d ([`lib/notifications/index.js`, lines 27 to 48](https://github.com/DemocracyOS/democracyos/blob/441de8ef25bf6751058c1b092a70729ad778f58d/lib/notifications/index.js#L27-L48)).
