### ISSUE TITLE
Make DemocracyOS requirable as an npm package

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#1076]
This would let us to use DemocracyOS directly and extend/modify it easily. The only two things that we need to fix is the `NODE_PATH` default value (we should use relative paths); and, to be able to give it a config object to the constructor.

How I see it e.g.:
```javascript
// on my custom index.js
var democracyOS = require('democracyos')

var app = democracyOS({
  config: require('./config/development.json')
})

app.get('/custom-page', myCustomPage)

app.listen(function(){
  console.log('DemocracyOS running!')
})
```

**Comment by jfresco** [comment]
I love that, but I don't find it useful for now.

**Comment by slifszyc** [comment]
I remember talking with @cristiandouce about this a long time ago.

I think it could be used to customize a DemocracyOS instance with new routes/views/logic.

:+1:

**Comment by jfresco** [comment]
I see it as a first approximation to a plugin system, which is a more ambicious goal.

**Comment by slifszyc** [comment]
I agree with @jfresco, it would be a more complex approach if we want the app to support plugins and stuff.

```
...

var democracyos = new DemocracyOS(config);
democracyos.use(facebookSignin);
democracyos.use(twitterSignin);
democracyos.use(hub);
democracyos.use(thishomepage);
democracyos.views('homepage', HomepageView);
```

that's more of a framework rather than an app...

**Comment by gvilarino** [comment]
+1 to @slifszyc and @jfresco - Plugins should look like `express`' middlewares, which is the standard approach under `node` environments.

When we discussed with @cristiandouce we were thinking about the UI/system being requirable as a `component`, but it was very early in our development process. After all the learned lessons and feedback we've been having, and the road development has been going down, it's hard for me to see `DemocracyOS` as a requirable package but instead I see it as a complete application, with severeal aditional dependencies and configurations that would be hard to adress with the proposed approach.

I do agree, however, with moving into a more modularized approach, in the form of microservices, so as we could have a more "use your own flavor of DemocracyOS". I envision different modules as embeddable/externalizable stuff which would allow not only one single deployment to run, but also external apps talking to different parts of DemocracyOS, hosted separately if need be.

For example:
* `id.democracyos.org` -> main identity provider. Would serve as auth backend for the DOS hub, but also as an `oauth` provider for third party applications.
* `app.democracyos.org` -> Main web application. Accepts plugins and can have embeddable sections.
* `topics.democracyos.org` -> main content provider. Where all content is stored. Highly cachable and could serve as a public API for opening up offcial data.
* `debates.democracysos.org` -> arguments, replies, etc.
And so on.

This is just a rough idea, not to be taken very seriously but as a conversation starter.

**Comment by mjlescano** [comment]
Totally agree with everyone on the mid and long term. But, I was thinking this issue as a quick and dirty way to extend DemocracyOS. It would allow us to test new features without having to fork it every time, and move that features to other instances seamlessly :wind_chime:

**Comment by gvilarino** [comment]
Quick and dirty testing can be easily achieved with just a `git clone DemocracyOS/app`; no fork needed for that.

**Comment by jfresco** [comment]
Let's do the exercise of thinking what is the use case of the developer forking our project and extending it. Typically, they
- add a landing page,
- add a button or some other widget to the sidebar,
- change some styles,
- ...

I think we can write some documentation aimed to the forkers explaining how to do that.

One disadvantage of making DemocracyOS `require`able is that we are adding a new scenario to our tests, causing some overhead to our development process.

**Comment by gvilarino** [comment]
> One disadvantage of making DemocracyOS requireable is that we are adding a new scenario to our tests, causing some overhead to our development process.

:point_up_2:
