### ISSUE TITLE
Docker for development

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#1078]
Following some recent conversations [on our gitter channel](https://gitter.im/DemocracyOS/app) I think it would be reasonable to provide a developer-friendly docker solution.

I have a pretty good idea about how we should address this, but I have some stuff I'd like to discuss.

Our main external dependency is `MongoDB`. This can be addressed in two ways:

1. Have a `MongoDB` server run inside the development container.
  * Pros
    * Running a local dev environment would just be `docker run -P democracyos-development`
    * [KISS](https://en.wikipedia.org/wiki/KISS_principle) FTW!
  * Cons
    * We'll have to decide whether to use one of the official `MongoDB` images as the base of our docker image (which has no useful tools like `vi` or `git`) or create (and maintain) a custom base image for our devs. In any case, our Dockerfile or docker build would be non-standard and require some complexity.
    * Unless we use an external dir for storing data, data would be los whenever the container is destroyed. And using external data dirs would also create a complexity by depending on the dev host's OS in some manner (e.g.: permission issues, etc.)

2. Have an additional container running `MongoDB` which we can link the dev container to.
  * Pros
    * Simple Dockerfile and setup process.
    * Dev container would be completely volatile with no risk of data loss.
  * Cons
    * We can't rely on `docker-compose` for orchestration since ATM it runs only on `OS/X`
    * Set-up will depend on people reding and following a guide under `README.md` or similar.

Thoughts?

**Comment by mjlescano** [comment]
@gvilarino The permissions problem on point `1` would still exist if we put the `DB` data on a `.tmp` folder inside the project? e.g. in `/DemocracyOS/app/.tmp/db` and then run mongo with `mongod --dbpath /DemocracyOS/app/.tmp/db`

**Comment by gvilarino** [comment]
I would never, ever put data inside the project path; it's not reasonable and would also sync them *inside* the container (for being in the project path).

**Comment by mjlescano** [comment]
Ok, nevertheless, I prefer the simplicity of point `1` with the official `MongoDB` image and using an internal `dir` for storage, because maintaining a short critical path to have a `dev` machine running correctly is essential.

Also, if the user wants something more customized/complex it can change the `mongoUrl` config.

**Comment by vladfr** [comment]
Hi! (just bumped into this project).

On Cons from 2)
- How about offering a docker-compose.yml for *nix, and writing a simple bash script that can build your app container, and start it together with a mongo container with its separate volume?
Windows users would run this script either through cygwin/msysgit or directly in the docker box.
`./app.sh build` # builds the local image
`./app.sh run` # starts both containers, calls `build` if needed
`./app.sh stop` # stops both
- this would make it easier to get started, the README section would be thin?

**Comment by gvilarino** [comment]
@vladfr when this issue was created `docker-compose` was available only for `OS/X` boxes; since it's also become available under *nix systems, I'm considering it even more. It still leaves windows development out of scope, tho.

Regarding your shell suggestions, I was thinking about the same thing, sort of, but I'll try leveraging `make` since it's our go-to CLI tool.

**Comment by jclagache** [comment]
I wanted to give DemocracyOS a try without having to install [the requirements](https://github.com/DemocracyOS/democracyos/wiki/Installation#requirements). I also thought it would make a good exercise to make progress with the [Docker Engine](https://www.docker.com/docker-engine) platform. I made [this gist](https://gist.github.com/8f80fa103606b18beb0f.git) that describe the configuration I choose.
Feel free to give it a try and bring your remarks. Obviously, i'm available to discuss about it.

**Comment by mjlescano** [comment]
Thanks @jclagache! I will give it a try.

As a note, we're deprecating the wiki, the installation requirements for `>1.0.0` are at http://docs.democracyos.org/install.html

**Comment by vladfr** [comment]
@mjlescano the docs look great. I actually tried making a Jessie vagrant VM, but node deps killed me. I'll give it another go this week-end. If no one is working on a Vagrantfile, is there any place where I can "assign" it to me? I'd really like to finish a working version.

@gvilarino "make" sounds good, although the Makefile format has some formatting issues with Docker. Namely, using _ or / in a variable name spits out nasty errors, and you may need that for the image name. Found that the hard way! In any case, it should not be a big issue.

Here's another alternative for Windows: write a specific wiki page for them and recommend Kitematic: https://docs.docker.com/kitematic/userguide/ 
The wiki page shows how to do a proper setup with 2 containers, volumes etc. and can be a good primer into Docker and its tools as well.

**Comment by gvilarino** [comment]
Thanks @vladfr I'll check that out

**Comment by vladfr** [comment]
@gvilarino I tried to run the Dockerfile in master, getting this:
module.js:340
    throw err;
          ^
Error: Cannot find module 'lib/config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/src/democracyos/app/index.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Is there a known fix, not sure how to solve. Should I open a new issue for this?

**Comment by slifszyc** [comment]
I will add this to the [wish list](https://github.com/DemocracyOS/democracyos/wiki/Wish-list-&-Must-include) no the wiki

**Comment by gvilarino** [comment]
I'm reopening this since #1213 provides a solution for this.

@jclagache @vladfr wanna check that out?
