### ISSUE TITLE
[homepage] - Update hub homepage

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/democracyos#1079]
- [x] Remove all references to `Feed` (model, db-api, api, feeds, views, config items)
- [x] Create new cards for showing forum title, short description and an image made with [Trianglify](http://qrohlf.com/trianglify)
- [x] Paginate all the forums on the homepage

**Comment by VictorW1** [comment]
High priority for our instance close to launch. Thanks for addressing.

**Comment by mjlescano** [comment]
Closed by #1086
