### ISSUE TITLE
App crashes when attempting to add two comments in a row.

### ISSUE THREAD

**Issue by danimcgoo** [DemocracyOS/democracyos#1080]
Installed on heroku using the magic button, then redeployed latest 1.0.0 branch. Created some topics, then tried to add arguments to them. The first argument is accepted, but on the second addition it crashes.

This is what appears on the client side...

<img width="805" alt="screen shot 2015-10-17 at 12 00 13 am" src="https://cloud.githubusercontent.com/assets/416173/10542216/505b7f94-7462-11e5-8b2d-cea02e2c0f3f.png">

This appears to be the key error:

`6.351 2015-10-16 12:59:59.867211+00:00 app web.1 - - /app/node_modules/democracyos-notifier/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:247
» 17 Oct 2015 00:01:26.351 2015-10-16 12:59:59.867215+00:00 app web.1 - - throw err;
» 17 Oct 2015 00:01:26.351 2015-10-16 12:59:59.867215+00:00 app web.1 - - ^
» 17 Oct 2015 00:01:26.351 2015-10-16 12:59:59.867216+00:00 app web.1 - -
» 17 Oct 2015 00:01:26.351 2015-10-16 12:59:59.867217+00:00 app web.1 - - TypeError: Cannot read property 'forum' of null at /app/node_modules/democracyos-notifier/lib/jobs/lib/topic-commented.js:17:47 at /app/node_modules/democracyos-notifier/node_modules/mongojs/lib/collection.js:51:5 at handleCallback (/app/node_modules/democracyos-notifier/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:244:5) at setCursorNotified (/app/node_modules/democracyos-notifier/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:554:3) at /app/node_modules/democracyos-notifier/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:661:16 at queryCallback (/app/node_modules/democracyos-notifier/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:321:5) at Callbacks.emit (/app/node_modules/democracyos-notifier/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:95:3) at null.messageHandler (/app/node_modules/democracyos-notifier/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:243:23) at Socket.<anonymous> (/app/node_modules/democracyos-notifier/node_modules/mongojs/node_modules/mongodb-core/lib/connection/connection.js:262:22) at emitOne (events.js:77:13)` Exception

» 17 Oct 2015 00:01:26.351 2015-10-16 13:00:00.326118+00:00 heroku web.1 - - Process exited with status 1
» 17 Oct 2015 00:01:31.988 2015-10-16 13:00:05.518664+00:00 heroku web.1 - - Starting process with command `gulp build && NODE_PATH=. PUBLIC_PORT=80 node index.js`
» 17 Oct 2015 00:01:31.988 2015-10-16 13:00:15.770825+00:00 app web.1 - - [13:00:15] Starting 'public'...
» 17 Oct 2015 00:01:31.988 2015-10-16 13:00:15.829772+00:00 app web.1 - - [13:00:15] Finished 'public' after 57 ms
» 17 Oct 2015 00:01:31.988 2015-10-16 13:00:15.829962+00:00 app web.1 - - [13:00:15] Starting 'js:build'...
» 17 Oct 2015 00:01:31.988 2015-10-16 13:00:15.934700+00:00 app web.1 - - [13:00:15] Starting 'assets'...
» 17 Oct 2015 00:01:43.398 2015-10-16 13:01:07.774245+00:00 heroku router - - at=error code=H10 desc="App crashed" method=POST path="/api/topic/561b69e1141f47100010d1ee/comment" host=sydney-democracyos.herokuapp.com request_id=ae1a1b7d-ebfb-4fd7-91ca-307681273f3e fwd="121.44.197.252" dyno= connect= service= status=503 bytes= Fatal
» 17 Oct 2015 00:01:47.179 2015-10-16 13:00:20.549950+00:00 app web.1 - - [13:00:20] Finished 'css:build' after 4.78 s
» 17 Oct 2015 00:02:32.487 2015-10-16 13:01:05.958351+00:00 heroku web.1 - - Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch Fatal
» 17 Oct 2015 00:02:32.568 2015-10-16 13:01:05.958351+00:00 heroku web.1 - - Stopping process with SIGKILL
» 17 Oct 2015 00:02:33.358 2015-10-16 13:01:06.982028+00:00 heroku web.1 - - Process exited with status 137
» 17 Oct 2015 00:02:33.399 2015-10-16 13:01:06.995637+00:00 heroku web.1 - - State changed from starting to crashed

This is the email I receive with the log entries.

App crashed: Heroku/sydney-democracyos

2015-10-16 13:01:09.278
346 <158>1 2015-10-16T13:01:08.903487+00:00 heroku router - - at=error code=H10 desc="App crashed" method=POST path="/api/topic/561b69e1141f47100010d1ee/comment" host=sydney-democracyos.herokuapp.com request_id=2cd62891-fc66-4009-bb3f-1e7fb62d3153 fwd="121.44.197.252" dyno= connect= service= status=503 bytes=

Go to the log: https://api.heroku.com/myapps/app42261606@heroku.com/addons/logentries

You are receiving this email because your Logentries alarm "App crashed"
has been triggered.

In context:
2015-10-16 12:59:33.562 309 <158>1 2015-10-16T12:59:33.281772+00:00 heroku router - - at=info method=GET path="/boot/logo-mobile.png" host=sydney-democracyos.herokuapp.com request_id=ca9de2d2-b5aa-4646-924e-4aaa82bf4577 fwd="121.44.197.252" dyno=web.1 connect=1ms service=3ms status=200 bytes=7797
2015-10-16 12:59:33.569 306 <158>1 2015-10-16T12:59:33.291297+00:00 heroku router - - at=info method=GET path="/tags/internet.svg" host=sydney-democracyos.herokuapp.com request_id=338031a6-de1e-4d8a-a48c-db9cda8b46af fwd="121.44.197.252" dyno=web.1 connect=0ms service=2ms status=200 bytes=1364
2015-10-16 12:59:33.866 362 <158>1 2015-10-16T12:59:33.670459+00:00 heroku router - - at=info method=GET path="/api/topic/561b69e1141f47100010d1ee/sidecomments?random=0.4972249350976199" host=sydney-democracyos.herokuapp.com request_id=0cdf5bed-23b8-41fb-b65b-2c1de162af39 fwd="121.44.197.252" dyno=web.1 connect=1ms service=57ms status=200 bytes=685
2015-10-16 12:59:33.868 322 <158>1 2015-10-16T12:59:33.642375+00:00 heroku router - - at=info method=GET path="/flaticons/flaticons-social.woff" host=sydney-democracyos.herokuapp.com request_id=a70a586e-d0bd-4a92-8fc0-fcb2d5089d39 fwd="121.44.197.252" dyno=web.1 connect=0ms service=13ms status=200 bytes=15048
2015-10-16 12:59:34.194 423 <158>1 2015-10-16T12:59:33.956482+00:00 heroku router - - at=info method=GET path="/api/topic/561b69e1141f47100010d1ee/comments?page=0&sort=-score&limit=0&exclude_user=5614cce10e63c410008c7eac&random=0.8121894956566393" host=sydney-democracyos.herokuapp.com request_id=f66c7956-534b-493f-85a6-0e8357809e69 fwd="121.44.197.252" dyno=web.1 connect=0ms service=11ms status=200 bytes=212
2015-10-16 13:00:00.515 128 <45>1 2015-10-16T13:00:00.340565+00:00 heroku web.1 - - State changed from up to crashed
2015-10-16 13:00:00.619 134 <45>1 2015-10-16T13:00:00.342063+00:00 heroku web.1 - - State changed from crashed to starting
2015-10-16 13:00:16.118 133 <190>1 2015-10-16T13:00:15.765706+00:00 app web.1 - - [13:00:15] Using gulpfile ~/gulpfile.js
2015-10-16 13:00:16.194 128 <190>1 2015-10-16T13:00:15.772469+00:00 app web.1 - - [13:00:15] Starting 'css:build'...
2015-10-16 13:00:39.564 133 <190>1 2015-10-16T13:00:39.263150+00:00 app web.1 - - [13:00:39] Finished 'assets' after 23 s
2015-10-16 13:01:09.278 346 <158>1 2015-10-16T13:01:08.903487+00:00 heroku router - - at=error code=H10 desc="App crashed" method=POST path="/api/topic/561b69e1141f47100010d1ee/comment" host=sydney-democracyos.herokuapp.com request_id=2cd62891-fc66-4009-bb3f-1e7fb62d3153 fwd="121.44.197.252" dyno= connect= service= status=503 bytes=

**Comment by VictorW1** [comment]
Same issue on Democracy OS ubuntu. 

Some things I note- Forum database seems to be empty.
Commenting out references to topic.forum doesn't seem to work

**Comment by VictorW1** [comment]
Maybe a question is- can I populate my feeds with a forum? if so, how is this done?
```
> db.feeds.find()
{ "type" : "topic-published", "topic" : "561f561a9b85a6102e148df6", "createdAt" : 1444894237250, "forum" : null, "_id" : ObjectId("561f561d89dc5b102ec35e6b") }
{ "type" : "topic-voted", "createdAt" : 1444894265092, "topic" : "561f561a9b85a6102e148df6", "forum" : null, "data" : { "user" : "561f54e29b85a6102e", "vote" : "neutral" }, "_id" : ObjectId("561f563989dc5b102ec35e6d") }
{ "type" : "topic-published", "topic" : "561f570c9b85a6102e148e16", "createdAt" : 1444894535983, "forum" : null, "_id" : ObjectId("561f574789dc5b102ec35e6f") }
{ "type" : "topic-voted", "createdAt" : 1444894794990, "topic" : "561f570c9b85a6102e148e16", "forum" : null, "data" : { "user" : "561f54e29b, "vote" : "negative" }, "_id" : ObjectId("561f584a89dc5b102ec35e71") }
{ "type" : "topic-published", "topic" : "561f5b29a03161752e3a32fb", "createdAt" : 1444895531732, "forum" : null, "_id" : ObjectId("561f5b2bc5") }
{ "type" : "topic-published", "topic" : "561f5c2ba03161752e3a3302", "createdAt" : 1444895788349, "forum" : null, "_id" : ObjectId("561f5c2cc59c117") }
{ "type" : "topic-published", "topic" : "561f5e0de77bb3bc2ee3eb98", "createdAt" : 1444896372689, "forum" : null, "_id" : ObjectId("561f5e74dd9408") }
{ "type" : "topic-published", "topic" : "561f5ebce77bb3bc2ee3ebc3", "createdAt" : 1444896487603, "forum" : null, "_id" : ObjectId("561f5ee7dd9408b") }
{ "type" : "topic-voted", "createdAt" : 1444896555999, "topic" : "561f5b29a03161752e3a32fb", "forum" : null, "data" : { "user" : "561f54e29b85a6", "vote" : "negative" }, "_id" : ObjectId("561f5f2bdd9408bc2e649bdf") }
{ "type" : "topic-voted", "createdAt" : 1444896559112, "topic" : "561f5c2ba03161752e3a3302", "forum" : null, "data" : { "user" : "561f54e29b85a", "vote" : "positive" }, "_id" : ObjectId("561f5f2fdd9408bc2e649be1") }
{ "type" : "topic-voted", "createdAt" : 1444896561995, "topic" : "561f5e0de77bb3bc2ee3eb98", "forum" : null, "data" : { "user" : "561f54e29b85a610", "vote" : "positive" }, "_id" : ObjectId("561f5f31dd9408bc2e649be3") }
{ "type" : "topic-voted", "createdAt" : 1444896564524, "topic" : "561f5ebce77bb3bc2ee3ebc3", "forum" : null, "data" : { "user" : "561f54e29b8", "vote" : "negative" }, "_id" : ObjectId("561f5f34dd9408bc2e649be5") }
> 
```

**Comment by slifszyc** [comment]
It's related to feeds creation. We're removing that feature in this issue anyways: https://github.com/DemocracyOS/app/issues/1079

**Comment by danimcgoo** [comment]
Hey I'm still seeing this error in 1.0.0? Is it meant to be closed yet?

**Comment by slifszyc** [comment]
I will reopen it

**Comment by VictorW1** [comment]
Can confirm still issue on 1.0.0 running in ubuntu. Related issue #1079 is still open - seemed that this was required work.

**Comment by ben-pr-p** [comment]
Seems like the problem is `democracyos-notifier` hasn't been updated since feed was removed. If you're looking for a quick hack, going into `node_modules/democracyos-notifier/lib/jobs/lib/topic-commented.js` and replacing the main function with this:

```
module.exports = function (opts) {
  db = db(opts.mongoUrl)
  opts.eventsAndJobs[jobName] = jobName

  opts.agenda.define(jobName, function (job, done) {
    var data = job.attrs.data

    db.topics.findOne({_id: ObjectId(data.topic)}, function (err, topic) {
      if (err) return log('Error found %s', err), done(err);

      done();
    })
  })
}
``` 
instead of this:
```
module.exports = function (opts) {
  db = db(opts.mongoUrl)
  opts.eventsAndJobs[jobName] = jobName

  opts.agenda.define(jobName, function (job, done) {
    var data = job.attrs.data

    db.topics.findOne({_id: ObjectId(data.topic)}, function (err, topic) {
      if (err) return log('Error found %s', err), done(err);

      db.feeds.findOne({ forum: ObjectId(topic.forum) }, function (err, feed) {
        if (err) return log('Error found %s', err), done(err);

        feed = feed || {}
        feed.type = jobName
        feed.createdAt = Date.now()
        feed.topic = data.topic
        feed.comment = data.comment
        feed.data = { user: data.user }
        feed.forum = topic.forum

        db.feeds.save(feed, function (err, feed) {
          if (err) return log('Error found %s', err), done(err)

          log('Saved feed for commented topic %s', data.topic)
          done()
        })
      })
    })
  })
}
```
will fix it.
