### ISSUE TITLE
Upgrade to Express 4

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#1081]
Or higher. More precisely higher than `4.13.3`, as we can see in [`david`](https://david-dm.org/DemocracyOS/app) eariler versions have security issues.

For doing this, I'd advice reading this article on how to move [to Express 4 from earlier versions](http://expressjs.com/guide/migrating-4.html), or more specificaly: [migrating to Express 4 from Express 3](https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x)

Alternatively, we can go to the latest `3.y.z` version, since [there are security patches](http://expressjs.com/advanced/security-updates.html) there as well, and upgrading to 4 will imply redoing part of our `boot` module, since many middlewares are no longer bundled with `express` itself (although it shouldn't be too much of a hassle).

**Comment by slifszyc** [comment]
:+1: 

we should test all `https` features as well

**Comment by gvilarino** [comment]
Agree. One thig to keep in mind is the following:

Our `https`-forcing mechanism relies on [`express-sslify`](https://github.com/florianheinemann/express-sslify) which, in turn, some consirations to keep in mind.

1. Express 4 will not work properly with redirection since `express-sslify` [uses `req.host` instead of `req.hostname` to determine the URL for redirection](https://github.com/florianheinemann/express-sslify/blob/master/index.js#L26) and the `url` core module we use [uses on `hostname` as the property name]https://github.com/DemocracyOS/app/blob/1.0.0/lib/utils/index.js#L271). Double-check that before closing this issue.

2. There is an [open pull request](https://github.com/florianheinemann/express-sslify/pull/6) that -if merged- will change `express-sslify`'s API (i.e.: it will remove the [boolean trap](ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html). Keep this in mind if bumping the dep; our `lib/server-factory/ssl-redirect.js` should be updated as well.

**Comment by gvilarino** [comment]
The [aforementioned pull request](https://github.com/florianheinemann/express-sslify/pull/6) is now merged, so we should keep an eye out for a newer release of `express-sslify` that will break our current usage.

**Comment by slifszyc** [comment]
We'll upgrade on `2.0`
