### ISSUE TITLE
Normalize forum name on creation

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#1084]
Forums should only accept URL-friendly names on creation, and our associated endpoints (i.e.: api/<forum-name>) should lower-case any input. The same should be done for anything in the URL path.

So: hostname.org/SOMEFORUM/TOPIC/444FFF should be interpreted as hostname.org/someforum/topic/444fff

**Comment by mjlescano** [comment]
@gvilarino could you elaborate?

**Comment by gvilarino** [comment]
Forums should only accept URL-friendly names on creation, and our associated endpoints (i.e.: `api/<forum-name>`) should lower-case any input. The same should be done for anything in the URL path

So: `hostname.org/SOMEFORUM/TOPIC/444FFF` should be interpreted as `hostname.org/someforum/topic/444fff`

**Comment by jfresco** [comment]
test

**Comment by jfresco** [comment]
test

**Comment by slifszyc** [comment]
we saw this today

`https://app.democracyos.org/generationavenir/topic/55f876492ad72f100099fefb` works but `https://app.democracyos.org/GENERATIONAVENIR/TOPIC/55F877312AD72F100099FF03` doesn't

**Comment by mjlescano** [comment]
The forum name was already beign normalized, but, nevertheless this issue is closed by #1085

**Comment by mjlescano** [comment]
This issue should only handle the redirection when the forum `name` is capitalized, not any part of the route. To avoid the uncapitalization of form params, and other unhandled errors.

**Comment by gvilarino** [comment]
anything in the valid path should be uncapitalized. Not `id` or some other form of data but yes for path segments (e.g.: `forum`, `topic`, `comment`, etc)
