### ISSUE TITLE
Drop tags

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/democracyos#1095]
Reasons:
- Tags are not translatable
- In a multi-forum scenario, tags are app-wide instead of forum-scoped
- Amount of icons is limited and hard to extend.
- They work as _categories_: you cannot assign more than one tag to a topic.

Reverting those drawbacks is expensive and it doesn't add any value.
I suggest to drop them and implement some _keywords_ feature: the topic creator can assign zero or more keywords (or _tags_ or _hashtags_) to a topic.

**Comment by mjlescano** [comment]
+1

I can't remember an instance that tags were useful.

**Comment by gvilarino** [comment]
I'm all for github-like tags

**Comment by slifszyc** [comment]
This was done in https://github.com/DemocracyOS/democracyos/pull/1152

Tags will be back in `2.0` in a new fashion way: separated between `categories` and `keywords`.
