### ISSUE TITLE
Sign-up flow should end in the forum where user creation started

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#1102]
If I sign up from the "whatever" `forum`, I should be redirected to it when I finish validating my email address, and the "browsing" link should take me back to it as well.

Redirect only to the hub home if signing up from the forum gallery.

**Comment by slifszyc** [comment]
You mean if you are reading a forum and click first on the `login` button on the header, and next on the `signup`?

**Comment by slifszyc** [comment]
Because, if you try to vote on a topic inside a forum and then you decide to signup, you end up receiving the correct reference link and you get redirected

**Comment by gvilarino** [comment]
Yes. I mean that the source context should always be kept for when signing up/signing in. If it is the *last seen* context or the *original* context, it can be discussed. My vote would go for *last seen*

**Comment by slifszyc** [comment]
This will change in `2.0` so we'll wait til then to solve this
