### ISSUE TITLE
Add forum location property

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/democracyos#1104]
- [x] User must be able to set its forum location in the forum form.
- [ ] The behavoir should be similar to Twitter's: we should suggest places, but the input is free. The list should show political areas such as neighborhood, state and country.
- [x] We should use an external API such as Google Maps API (I'm open to discuss this).
- [x] The data should be stored in a structure in which the system be able to find nearby forums.

**Comment by slifszyc** [comment]
We'll review this feature on `2.0`
