### ISSUE TITLE
Fix sender name in notification emails

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#1106]
![screen shot 2015-10-27 at 3 16 56 pm](https://cloud.githubusercontent.com/assets/2538465/10768018/d04e2b1c-7cbd-11e5-991c-8c75fe6c3ec8.png)

That doesn't seem right. It seems to be based in the `ORGANIZATION_NAME` setting. It shouldn't be. At least not for us.

**Comment by slifszyc** [comment]
Environment variable set

**Comment by gvilarino** [comment]
This is not a proper way of solving this. This is a parameter that [should be passed to `notifier`](https://github.com/DemocracyOS/notifier/blob/development/index.js#L12-L13) instead of doing something that changes our header text.
