### ISSUE TITLE
Not redirecting to homepage when user is logged in and tries to signup/signin

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#1107]
This should not happen.

![screen shot 2015-10-27 at 3 22 39 pm](https://cloud.githubusercontent.com/assets/2538465/10768215/c0a4e84e-7cbe-11e5-8010-45ef04cf9fb9.png)

**Comment by slifszyc** [comment]
I don't know if I get what's wrong here. There's no inconsistent session, just a missing redirect to `/` if the user is logged in.

Or I am missing something else?

**Comment by gvilarino** [comment]
I don't know, I just shared the symptom and repro. Can you repro?

**Comment by slifszyc** [comment]
Yup, I'm just gonna change the issue title as it's not the issue, just a missing redirect to home if the user is logged in.

**Comment by gvilarino** [comment]
:+1:
