### ISSUE TITLE
Set properly notifications language

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/democracyos#1116]
In spite of `notifier` supports many languages, embedded notifications are [always sent in english](https://github.com/DemocracyOS/notifier/blob/development/lib/templates/index.js#L13).
I think we must set the language on client side, like this:
```js
notifier.notify(event)
.to(user.email)
.withData( { validateUrl: validateUrl } )
.language(user.locale)
.send(function (err, data) {
  // ...
})
```

The aim is all users to receive notifications in her languages.

This also requires modifications on `notifier` and `notifier-client`.

**Comment by gvilarino** [comment]
`notifier` [already supports](https://github.com/DemocracyOS/notifier/blob/a572ab2d52e23b4582706ada02d22fa0dc9bfb2a/lib/templates/index.js#L13) language/locale as a parameter. We're probably just not setting the option correctly.

**Comment by jfresco** [comment]
@gvilarino AFAIS `opts.lang` is always `undefined`.

**Comment by gvilarino** [comment]
@jfresco because [it's not being specified](https://github.com/DemocracyOS/democracyos/blob/master/lib/server/index.js#L40-L48) :sweat_smile:

**Comment by jfresco** [comment]
@gvilarino Yeah, but my point is that you don't have to set the language on server boot, because you are setting on language for _all_ users, and each user could have a differente language. My point is that we have to set the notification language when we are _sending_ the notification (see the portion of code in my first comment).

**Comment by gvilarino** [comment]
Yeah, you gotta code that :D

**Comment by jfresco** [comment]
:+1:
