### ISSUE TITLE
Allow posting comments or replies with CMD+Enter

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#1117]
Or Ctrl+Enter in Win/Linux.

Because, nerd.

**Comment by ben-pr-p** [comment]
How will the software know whether it's a reply or comment?

**Comment by slifszyc** [comment]
When you're writing a comment on a `textarea` and you press `cmd+enter` it should get posted, as it works in this very `textarea`

**Comment by slifszyc** [comment]
Closed in 51672df14e2e6518b9731e9a7592a3b5f192694c

thanks @ben-pr-p !
