### ISSUE TITLE
Add Report Abuse workflow for forums

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/democracyos#1120]
It has to be aligned with the terms of service.

Proposed use case:
- A link will be shown on the forum (with a flag icon or the label "Report abuse")
- When a user clicks that link, will see a modal form selecting one of many reasons why he considers it's an abuse.
- When the user submits the form, a notification will be delivered to a staff member, who will has the ability to suspend the forum.

**Comment by slifszyc** [comment]
We should have a superadmin for us (`staff` members) to control that for all forums

Not now, maybe in `DemocracyOS 2.0`.
