### ISSUE TITLE
Link for large image in articles

### ISSUE THREAD

**Issue by johnfelipe** [DemocracyOS/democracyos#1124]
http://proyectosdeordenanza.asambleadelosaraucanos.co:3000/topic/563acb27594c65d8076ca73d

Is possible add link in large image for possible zoom?

**Comment by mjlescano** [comment]
For that type of info, the "Link" functionality is more useful:

![captura de pantalla 2015-11-09 a las 15 04 35](https://cloud.githubusercontent.com/assets/558901/11041969/4b8465be-86f3-11e5-8cd8-d3c78c43d9f7.png)
