### ISSUE TITLE
Translation to spanish

### ISSUE THREAD

**Issue by johnfelipe** [DemocracyOS/democracyos#1125]
![screenshot_2015-11-05-01-50-44](https://cloud.githubusercontent.com/assets/428820/10961755/e5225bc8-835f-11e5-89e2-6275e160d242.png)

Read more
An hour ago

Still english

**Comment by slifszyc** [comment]
We already have an issue for this https://github.com/DemocracyOS/democracyos/issues/1039

Thanks for reporting it though, we're gonna take a look at it, but I'm closing this one as it's duplicated
