### ISSUE TITLE
Remove unused modules on `/lib` folder

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#1129]

**Comment by slifszyc** [comment]
:+1:

**Comment by patcon** [comment]
Can someone tell me where I would look to find the context on all these removed libs (and presumably features)? I was always most excited about the delegation feature in DemocracyOS, but it seems it has been removed?

Where do project discussions happen, so that I can catch myself up?

Thanks!

**Comment by mjlescano** [comment]
HI @patcon! Go to https://gitter.im/DemocracyOS/democracyos :)
