### ISSUE TITLE
In new Democracyos 1.0.1 dont show me create articles in admin UI

### ISSUE THREAD

**Issue by johnfelipe** [DemocracyOS/democracyos#1131]
in DOS 0.9 is this:

![articlesdos](https://cloud.githubusercontent.com/assets/428820/11042211/e3392d6e-86e3-11e5-9891-123b6f58e41f.png)

And "Lee más" is enable

In DOS 1.0.1 is not

**Comment by jfresco** [comment]
_Read More_ and _clauses_ (articles) features have been deprecated in `1.0.1`.
Check the [migration guide](https://github.com/DemocracyOS/democracyos/wiki/Migrating-to-1.0) to see how to migrate your existing data.
