### ISSUE TITLE
Permalink for Arguments

### ISSUE THREAD

**Issue by martinvol** [DemocracyOS/democracyos#1135]
The argument's tag:
```html
 <li class="media comment-item">
```
 could have an id atribute with a unique identifier. Like this:

```html
<li class="media comment-item" id=100>
```

This way when the user receives a notification it can link directly to his argument. Like this: dos.xxx.org/law/XXXX#100

**Comment by slifszyc** [comment]
This is not possible as comments are loaded asynchronously :(
