### ISSUE TITLE
When the login has error, part of inputs aren't selectable

### ISSUE THREAD

**Issue by agustin107** [DemocracyOS/democracyos#1137]
When selected the input on the error area, this it's not selectable.

![screenshot from 2015-11-14 02 33 15](https://cloud.githubusercontent.com/assets/2467822/11162264/a86250e2-8a78-11e5-88b6-8bcc25febcd1.png)

**Comment by mjlescano** [comment]
Pretty sure this could be easily fixed with `pointer-events: none;`

https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events
