### ISSUE TITLE
Implement per forum permission model

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/democracyos#1143]
- [x] All forums have to have and owner (creator), admins and collaborators.
- [x] The owner can add admins and collaborators, and decide if the forum is public or private.
- [x] The admin can add collaborators but not other admins.
- [x] The collaborators can comment and vote if the forum is private.
- [x] Update UI
- [x] Document

**Comment by mjlescano** [comment]
@jfresco is this duplicated? #1069 #1070

**Comment by jfresco** [comment]
Mmm... I think related, not duplicated.
