### ISSUE TITLE
Votes are public / insecure

### ISSUE THREAD

**Issue by ben-pr-p** [DemocracyOS/democracyos#1145]
If I open up my console and throw a debugger somewhere in `lib/proposal-options/proposal-options.js`

<img width="1440" alt="screen shot 2015-11-18 at 11 35 29 am" src="https://cloud.githubusercontent.com/assets/10324926/11243861/3cb9c3ce-8de9-11e5-9608-6cc3286fd9c2.png">

I can see the UserId of the upvotes, downvotes, etc.

<img width="1440" alt="screen shot 2015-11-18 at 11 36 16 am" src="https://cloud.githubusercontent.com/assets/10324926/11243865/44e16c78-8de9-11e5-8f29-5aa6f0d07c0a.png">

Then I can throw another debugger somewhere in `lib/participant-view/view.js` and see who that UserId corresponds to

<img width="1440" alt="screen shot 2015-11-18 at 11 40 32 am" src="https://cloud.githubusercontent.com/assets/10324926/11243887/66f21f74-8de9-11e5-9bfe-71c5c12dec03.png">

Should I fix this?

**Comment by ben-pr-p** [comment]
I suppose it should be:
```
If open:
     only send user vote, total number of participants, and total votes cast
If closed:
     send length of each vote section + user vote

**Comment by slifszyc** [comment]
Closed as said here https://github.com/DemocracyOS/democracyos/pull/1146#issuecomment-163710855
