### ISSUE TITLE
jsdom 4.x onward only works on io.js, not Node.js

### ISSUE THREAD

**Issue by maop** [DemocracyOS/democracyos#1148]
Hello,

I'm very sorry if this isn't the place to report this issue, i just keep facing this "wall" and can not advance at installing democracyos, also i'm noob with Node and googling have not gave me some solution.

whenever i run `make` it stops at:

`jsdom 4.x onward only works on io.js, not Node.js`

i have tried with ubuntu 14.04 and 15.10 with and without nodejs-legacy.

Please if someone have had this same issue let me know how to work it around.

thanks in advanced, best regards!

**Comment by jfresco** [comment]
You have to use Node 4.x.
We recommend to use https://github.com/tj/n to switch between Node versions.
