### ISSUE TITLE
Installation problems: missing dependencies

### ISSUE THREAD

**Issue by dalareo** [DemocracyOS/democracyos#1150]
I've found that there are at least three missing packages when installing on Ubuntu/Debian:

    libcairo2-dev
    libpango1.0-dev
    libjpeg-dev

I still get error messages when executing, any other missing dependency??

**Comment by dalareo** [comment]
libkrb5-dev 
is also needed

**Comment by slifszyc** [comment]
but can you start the app though?

**Comment by dalareo** [comment]
Yes, once resolved the missing dependencies.

**Comment by slifszyc** [comment]
But is it just a warning message and the app starts normally or you have to manually install those packages before starting the app?

**Comment by dalareo** [comment]
I had to manually install those packages before

**Comment by slifszyc** [comment]
Check out this commit https://github.com/DemocracyOS/democracyos/commit/ced12648eca4d5970963f5a34c164f547dece0e3 please tell me if it fixes it on your OS

**Comment by slifszyc** [comment]
@dalareo did it work? it's due to a dependency we have called [trianglify](https://github.com/qrohlf/trianglify) which we'll be removing in the next weeks

**Comment by dalareo** [comment]
I cannot tell you I it works once I have installed the dependencies. I should uninstall them all back again. Maybe we could try with an empty Ubuntu 14.04 machine.

**Comment by slifszyc** [comment]
any news regarding this issue @dalareo?

**Comment by dalareo** [comment]
No error show when building now
