### ISSUE TITLE
On sidebar, multiple properties of the topics should be divided by newlines

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#1159]
![captura de pantalla 2015-12-04 a las 14 48 11](https://cloud.githubusercontent.com/assets/558901/11596803/2afeb694-9a96-11e5-957e-220be68e72b3.png)

**Comment by slifszyc** [comment]
Closed in 130f74d454d25dc0e4ee2088a216ec38286a28d8
