### ISSUE TITLE
confirmation email - only a template is arriving

### ISSUE THREAD

**Issue by kiazami** [DemocracyOS/democracyos#1166]
On democracyOS

**Comment by slifszyc** [comment]
do you have any screenshots? I'm getting the email correctly...

**Comment by kiazami** [comment]
Does this working?
---------- Továbbított üzenet ----------
Feladó: "The DemocracyOS Team" <no-reply@democracyos.org>
Dátum: 2015. dec. 17. 11:52
Tárgy: templates.welcome-email.subject
Címzett: "Csaba Madarász" <madarasz.csaba@gmail.com>
Másolatot kap:

templates.email.greeting

templates.welcome-email.body

templates.email.signature

templates.welcome-email.ps

**Comment by slifszyc** [comment]
did it occurred on https://app.democracyos.org/ or on your development environment?

**Comment by kiazami** [comment]
On  the  official  site
2015. dec. 17. 15:54 ezt írta ("Sacha Lifszyc" <notifications@github.com>):

**Comment by slifszyc** [comment]
ok I see it now, this issue belongs to [notifier](https://github.com/democracyos/notifier)

**Comment by slifszyc** [comment]
it's related to the languages available the [notifier](https://github.com/democracyos/notifier) app

this might end up being in the same repo as notifier alone makes no sense anymore

**Comment by kiazami** [comment]
Ok. I do not know what does it mean :)
But did this thing helped anyway?

**Comment by slifszyc** [comment]
yeah totally, we'll be fixing it in the next weeks

thanks a lot man!

**Comment by kiazami** [comment]
Hey,

for sure! I am that kind of a guy, who always ask from the menu, what they
do not have right now :)
It is helpful in software projects, by accident..

However, we are planning to launch another Hungarian installation of D.OS.
If we are chatting now - do you plan to adopt different voting models: like
borda, schulze beside yes/no?
And what is your relation with Consul - applied in Madrid/Barcelona

Cheers and thanks a lot!
Csaba


Madarász Csaba
+36703643482
madarasz.csaba@gmail.com
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX43MhM74Vd_Vfn8pTpQCVRrZFz56dH_cdzBYNb02?t=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fmcsaba&si=4619409677090816&pi=6b0ac29f-f97f-41d8-decb-6148d5f6316f>
LinkedIn
http://www.uvegfalu.hu

2015-12-18 13:24 GMT+01:00 Sacha Lifszyc <notifications@github.com>:

**Comment by semikolon** [comment]
I had this issue just now. Catastrophic since I can't confirm my account, no? It's not fixed yet? I'm from Sweden, so I guess that's the translation that's missing in my case.

**Comment by mjlescano** [comment]
just fixed it :D :point_up:
