### ISSUE TITLE
Unable to parse es6 locally

### ISSUE THREAD

**Issue by gdpelican** [DemocracyOS/democracyos#1167]
Hey DemocracyOS!

When trying to run a local instance of DemocracyOS, and am coming upon this error:
![screen shot 2015-12-19 at 9 39 08 am](https://cloud.githubusercontent.com/assets/750477/11912245/17b24a4c-a635-11e5-9603-98a58796eccb.png)

Which I'm assuming is because it isn't recognizing the new es6 fat arrow syntax. I have es6 installed on my machine globally, and have been able to run other es6 apps with it.

What am I missing? <3

**Comment by slifszyc** [comment]
upgrade your `node` version

I'm using `4.2.1` and it works fine
