### ISSUE TITLE
documentation lacking if I want to do initial setup of mongo on a separate machine

### ISSUE THREAD

**Issue by bkwdesign** [DemocracyOS/democracyos#1181]
This is my first time to deal with mongo - so, it may also be my extreme naivete on display here...

My client wants me to build out a development Democracy OS on two separate machines - one for running the web app, one for the Mongo DB

I've updated the mongo db URL in my config/development.json (but, this mongo DB server I'm pointing to does not have a 'DemocracyOS-dev' collection on it yet.. remember I'm starting from scratch)

 the 'make' seems to succeed and it goes into 'launching' .. but.. then I get this error (which I totally expected)

	  democracyos:translations   - validators.invalid.forum +0ms
	  democracyos:db Using mongodb hosts: XXX.XXX.XXX.XXX:27017 +208ms
	  democracyos:db Using mongodb URI: mongodb://XXX.XXX.XXX.XXX:27017/DemocracyOS-dev +0ms
	  democracyos:db Connecting to MongoDB database DemocracyOS-dev +1ms
	/usr/local/src/GitRepos/democracyos/lib/notifications/index.js:30
	var notify = event => {
			            ^
	SyntaxError: Unexpected token >
	    at Module._compile (module.js:439:25)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Module.require (module.js:364:17)
	    at require (module.js:380:17)
	    at Object.<anonymous> (/usr/local/src/GitRepos/democracyos/lib/db-api/comment.js:21:16)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)

**TL,DR**
What script or command do I need to run if I want to initialize the database before I run my "make" command?

**Comment by slifszyc** [comment]
If you're running it locally, then you should start your mongodb with the `mongod` command

**Comment by mjlescano** [comment]
Are you using Node v4+? The error that you're showing is because node is not recognizing the [Arrow Function](http://www.2ality.com/2012/04/arrow-functions.html) available since [Node v4+](https://nodejs.org/en/blog/release/v4.0.0/).

Also, just for clarification, `DemocracyOS-dev` is the name of the database itself, inside that database, `mongoose` dynamically creates all the collections on startup (using as reference the schemas at `/lib/models`). So, it shouldn't be necessary to initialize it beforehand.

**Comment by bkwdesign** [comment]
@slifszyc - the mongodb is definitely running - that's not the issue.. 

@mjlescano  - I'm running `v0.12.9`  - fwiw, I just cleared all node installations from my `Ubuntu 14.04.3 LTS` per the guidance [here](http://www.hostingadvice.com/how-to/install-nodejs-ubuntu-14-04/) - using the latest distribution [node-v0.12.9-linux-x64.tar.gz](http://nodejs.org/dist/latest-v0.12.x/node-v0.12.9-linux-x64.tar.gz)

when I run npm install to zip through all the packages, most succeed, but I can see a few `gyp` errors

**Comment by slifszyc** [comment]
That problem is due to the arrow function call in 

```
var notify = event => {
...
} 
```

Please update your node version to `^4.0.0` for it to work correctly

**Comment by bkwdesign** [comment]
FWIW - I switched from trying to build out the database on a separate machine.. now I have it all on one machine.. so.. I think there's definitely some kind of problem with the overall node installation - particularly the "noticiation" or "notify" piece...

Here's my latest error stack..

	  democracyos:db Using mongodb hosts: localhost:27017 +262ms
	  democracyos:db Using mongodb URI: mongodb://localhost:27017/DemocracyOS-dev +0ms
	  democracyos:db Connecting to MongoDB database DemocracyOS-dev +1ms
	/usr/local/src/GitRepos/democracyos/lib/notifications/index.js:30
	var notify = event => {
			           ^^
	SyntaxError: Unexpected token =>
	    at exports.runInThisContext (vm.js:73:16)
	    at Module._compile (module.js:443:25)
	    at Object.Module._extensions..js (module.js:478:10)
	    at Module.load (module.js:355:32)
	    at Function.Module._load (module.js:310:12)
	    at Module.require (module.js:365:17)
	    at require (module.js:384:17)
	    at Object.<anonymous> (/usr/local/src/GitRepos/democracyos/lib/db-api/comment.js:21:16)
	    at Module._compile (module.js:460:26)
	    at Object.Module._extensions..js (module.js:478:10)

**Comment by bkwdesign** [comment]
Ok, thanks.. going to try installing [node-v4.2.5-linux-x64.tar.gz](http://nodejs.org/dist/latest-v4.x/node-v4.2.5-linux-x64.tar.gz)

**Comment by slifszyc** [comment]
:+1: 

Please tell us how did it go

**Comment by bkwdesign** [comment]
Running `npm install` from the root of the democracyOS repo... all goes mostly smooth.. but...

![gyperror-brian democracy-1_ _usr_local_src_gitrepos_democracyos](https://cloud.githubusercontent.com/assets/3177513/12494054/40d551c2-c056-11e5-9d98-4bf6af91ed06.png)


and here..

![2016-01-21 15_43_11-brian democracy-1_ _usr_local_src_gitrepos_democracyos](https://cloud.githubusercontent.com/assets/3177513/12494079/631bf3f8-c056-11e5-94bb-c515e93d168f.png)

**Comment by bkwdesign** [comment]
I originally had `nodejs-legacy` installed per one of the DemocracyOS installation notes that I saw.. but, got similar errors regardless.

**Comment by bkwdesign** [comment]
However - I think we have success in spite of the above errors!
![successdemocracyos](https://cloud.githubusercontent.com/assets/3177513/12494203/e05fa346-c056-11e5-9a46-f44578ed2f70.png)
