### ISSUE TITLE
Support of accented characters

### ISSUE THREAD

**Issue by balessan** [DemocracyOS/democracyos#1182]
After having deployed an instance of DemocracyOS on Heroku here: http://av-democracyos.herokuapp.com/ I got an issue with the french î accented characters when trying to signup.

In signup -> Firstname field - Benoît is raising an "Invalid firstname" error, while Benoit is ok.

Not a big thing though, and not a prior bug for sure.

**Comment by kooparse** [comment]
#1184

**Comment by kooparse** [comment]
#1184

**Comment by mjlescano** [comment]
Closed by #1184
