### ISSUE TITLE
Live demo not working http://demo.democracyos.org/

### ISSUE THREAD

**Issue by viktorsmari** [DemocracyOS/democracyos#1185]
Will this be up again for testing?
[http://demo.democracyos.org/](http://demo.democracyos.org/)

**Comment by mjlescano** [comment]
Hi! Now you can use http://app.democracyos.org/ directly.

**Comment by viktorsmari** [comment]
Ok, thanks!

I created a pull request #1186 which replaces the broken link in the readme.
