### ISSUE TITLE
Email notifications with deep linking

### ISSUE THREAD

**Issue by Annagramma** [DemocracyOS/democracyos#1187]
This could be more engaging than linking to the general discussion, without pointing out the reason of the notification. For example, links could show the comment replies.
![image](https://cloud.githubusercontent.com/assets/4205060/13119911/2b3c1672-d58a-11e5-8c70-812b74dc8cae.png)

**Comment by franciclo** [comment]
Good idea, this could be tricky though, because comments are now paginated (making this experience worst actually), we should provide the comment id in the URL so the backend can show this comment first, and the front should know when this happen so it can scroll down to the comment.

**Comment by mjlescano** [comment]
what about adding an url like `/:forum/topics/:id/comments/:id` that only shows that comment, and a link that says something like "< go back to the topic"

**Comment by franciclo** [comment]
We have consider this for next major release.
