### ISSUE TITLE
asking password recovery of an unconfirmed account takes to Internal Error 500

### ISSUE THREAD

**Issue by mauriziomarini** [DemocracyOS/democracyos#1189]
use case of an average skilled final user:
- I sign-up
- a confirmation email is sent to me, confirmation email goes to (e.g) gmail spam  and I do not see it, 
- I don't answer confirmation email  and I am not a "confirmed" account
- I complain all the saints as I am not able to get in, so I try to change my password w/out any good reason
- I get Internal Error 500 as my account is unconfirmed
- I am lost in space

**Comment by impishj** [comment]
Same

**Comment by mjlescano** [comment]
This is already fixed on `add-react` branch, soon to be merged to `master` :)
