### ISSUE TITLE
Add IMPLEMENTATIONS.md file

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#1191]
... with a list of all the implementations out there that want to be listed on the main repo.

**Comment by Annagramma** [comment]
Around the world, many organizations are using DemocracyOS to encourage civic participation. 
Here you can find them :)

PS. Let us know if you are also part of the DemocracyOS galaxy!

[Partido de la Red - Buenos Aires, Argentina](http://dos.partidodelared.org)

[Municipio de Bahía Blanca, Argentina](http://bahiablanca.democracyos.org)

[Cámara Municipal de São Paulo, Brazil](http://euvoto.org)

[Barcelona en Comú - Barcelona, Spain](http://preprograma.barcelonaencomu.cat/)

[OpenCop21 - France](http://app.opencop.org/)

[D-Cent Project- Finland](http://finnish-democracyos.herokuapp.com/)

[Círculo I+D Podemos - Spain](http://podemos-id.herokuapp.com/)

[EVoks - Hungary](http://evoks.hu/)

[Mujer y Poder - Buenos Aires, Argentina](mujerypoder.democracyos.org)

[Asamblea Partido de la Red - Buenos Aires, Argentina](http://asamblea.partidodelared.org)

[Partido de la Red Colombia - Colombia](http://pdrcolombia-democracyos.herokuapp.com)

[Réforme du collège - France](http://college.democracyos.eu/)
