### ISSUE TITLE
Fix social shares links

### ISSUE THREAD

**Issue by votedave** [DemocracyOS/democracyos#1199]
I'm getting 404 issues with links to my democracy, those coming out of facebook. Can cut and paste URL in browser to get to site but the FB post link goes 404.

any ideas?

**Comment by mjlescano** [comment]
Hmm, not getting where you are having the error. Can you post the url that's wrong? Maybe an image?

**Comment by mjlescano** [comment]
Closing this 'til we know if it's really a bug

**Comment by votedave** [comment]
It's something going on, I'm just clicking and this is what's outputting - consistently - bug?
![01 link from page](https://cloud.githubusercontent.com/assets/17741338/14585883/505ea69c-04b8-11e6-9bf6-d3ce0bfd5925.JPG)
![02 output](https://cloud.githubusercontent.com/assets/17741338/14585884/5064e7dc-04b8-11e6-8d29-720c3dfd3b38.JPG)
![03 fb post](https://cloud.githubusercontent.com/assets/17741338/14585885/507c8eb4-04b8-11e6-9d6f-704c03e9431f.JPG)
![04 click the link sad face](https://cloud.githubusercontent.com/assets/17741338/14585886/5083d1b0-04b8-11e6-982e-435e9b99cddf.JPG)

**Comment by mjlescano** [comment]
@votedave Thanks!

The url is wrongly generated by the facebook share, it should be `/:forum/topic/:id`.

**Comment by votedave** [comment]
thanks team.  will check to see how it works now.  cheers

**Comment by votedave** [comment]
OK checked and still 404ing - problem still absolutely live and problematic - same issues

**Comment by mjlescano** [comment]
Now it's fixed 💃
