### ISSUE TITLE
Internal vs. external host and port

### ISSUE THREAD

**Issue by pbouda** [DemocracyOS/democracyos#1200]
We are trying to install Democracy OS at a cloud provider, where we need to set the host and port to "0.0.0.0:8080". A proxy is then making the app available on a domain name at port 80 and 443. The URL that Democracy OS builds are incorrect then, for example for the signup mail, when I set the config options to the internal ip/port. Is there any way to set an internal port and IP, but use another port and domain to contruct the URLs?

**Comment by mjlescano** [comment]
Hi!, Use the environment var `PORT=8080` to run it on that port, and set `PUBLIC_PORT=80` to set it as the "external" port. More info: https://github.com/DemocracyOS/democracyos/blob/master/index.js#L7

**Comment by pbouda** [comment]
Ok, thanks. Is there something similar for the hostname that is used to construct the URLs?

**Comment by mjlescano** [comment]
Yup, the `HOST` variable: http://docs.democracyos.org/configuration.html#-host-
