### ISSUE TITLE
Improve flexibility for embebed notifier configuration

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#1211]
More info: https://github.com/DemocracyOS/notifier/issues/20

**Comment by gvilarino** [comment]
I guess adding a `nodemailer` element to the config json could become additional `nodemailer` config options considered by `notifier`

**Comment by mjlescano** [comment]
Done: https://github.com/DemocracyOS/democracyos/commit/9e0f99d719bfca8c8e9f037ac3e0e2eb13087456
