### ISSUE TITLE
Double click on Send button = argument/response is posted twice

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyOS/democracyos#1212]
Hey guys, 

I've noticed that if a user clicks twice on the `send button` when posting an argument or a reply the app publishes it twice. I've been noticing this user behaviour mainly on mobile, when the server or the internet connexion lags a bit they tend to tap twice creating duplications.

<img width="579" alt="capture d ecran 2016-05-08 a 11 47 17" src="https://cloud.githubusercontent.com/assets/11473995/15097141/a572bc94-1512-11e6-8a1f-0de6b6817375.png">

Cheers

**Comment by mjlescano** [comment]
This is already fixed on `add-react`, soon to be merged to `master`.
