### ISSUE TITLE
Dev-love addition ideas💡

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#1214]
This issue is to discuss new techs to add, or to change the way we do things. Here we can generate a resume (wish-list?) of the things that are coming tech wise.
### Dev Process 📋
- [GitHub Projects](https://github.com/DemocracyOS/democracyos/projects) for issue management.

### Code Quality 🎨
- [Greenkeeper](https://greenkeeper.io/): Always up-to-date npm dependencies. ✔
- [Travis CI](https://travis-ci.org/): Continuous integration.
- [Hound CI](https://houndci.com/): Comments on style violations in GitHub pull requests.
- [JavaScript Standard Style](https://github.com/feross/standard): Done https://github.com/DemocracyOS/democracyos/pull/1179 ✔
- [`publish-please`](https://github.com/inikulin/publish-please/) for easy `npm publish` with version bumps.

### Testing ✅
- Starting point should be https://github.com/DemocracyOS/notifier/pull/21 with ❤️ by @jfresco and @SebastienDaniel 
- [Mocha](http://mochajs.org/) as test framework.
- [Chai](http://chaijs.com/) as assertion lib.
- [Sinon.js](http://sinonjs.org/) test spies, stubs and mocks for JavaScript.
- **Integration and Funcional tests:** TBD.

### Docker 🐳 ✔
- **Development:** https://github.com/DemocracyOS/democracyos/pull/1213 with ❤️ by @gvilarino ✔
- **Production:** https://github.com/DemocracyOS/democracyos/blob/master/Dockerfile#L25 ✔

### Techs 💾
- [React](https://facebook.github.io/react/): Partially done on [`add-react`](https://github.com/DemocracyOS/democracyos/tree/add-react) branch. Soon to be merged to `master`. ✔
- [Redux](http://redux.js.org/): as a predictable state container.
- [Draft.js](https://facebook.github.io/draft-js/): the way to go for rich text editing using React. (Some discussion [here](https://github.com/DemocracyOS/quill/pull/4))
- [WebPack](https://webpack.github.io/docs/): for optimized bundling of js modules.

### Security 👮
- [Snyk.io](https://snyk.io/): Dependencies vulnerabilities finder. ✔
- [Helmet.js](https://github.com/helmetjs/helmet): secure the app by setting various HTTP headers.

**Comment by franciclo** [comment]
### Module bundling
* [WebPack](https://webpack.github.io/docs/) for optimized bundling of js modules, and other ui dependencies like css or svg, its so much more flexible than browserify, by allowing to make differents bundles for entry point, sepparating common chunks of code, or code splitting for on demand async module loading. Also you can require any file that needs compiling like .styl or .jade and compile it using webpack loaders.

**Comment by VictorW1** [comment]
Is a simple Api for accessing the system via an external third party web and mobile app a possibility? We discussed this last year not sure if it was implemented.

**Comment by gvilarino** [comment]
@VictorW1 I think so, but still, our backend is a REST API in itself, so I'd like to discuss more on that matter. What would you expect from that? Are you referring to having some sort of API-only token-based auth for REST calls?

**Comment by SebastienDaniel** [comment]
### Testing
I totally approve of Mocha, Chai, Sinon. They're proven and ubiquitous unit testing solutions.

### Module bundling
I'm partial to browserify, but that's just a question of habit. I've hit some issues/limitations with it where by compilation steps are become unnecessarily hackish. If WebPack can circumvent that, I'm all for it.

### Techs
Redux is a godsend when state is becoming complex. I totally approve of it.

### Code quality
I'm all for standardized syntax & linting, I think it's critical in any decent-sized project. 

But for the love of god, I cannot comprehend the *pseudo-standardization of no-semicolons*, which is a core syntax element of almost all c-based languages. Even in their [spec](https://github.com/feross/standard/blob/master/RULES.md#semicolons) they say to prepend IIFEs with a semicolon. And for that reason alone I am against Javascript Standard Style.

*my two cents* :)

**Comment by mjlescano** [comment]
Thanks @SebastienDaniel, added Sinon to the list :)

About `;`'s: Oh no! [this](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) all over again.

There's no gain on discussing it, so, I'm totally in for reacting to this comment with:
* 👍 for YES Semicolons (using [Semistandard](https://github.com/Flet/semistandard))
* 👎  for NO Semicolons (using [Standard](https://github.com/feross/standard))

**Comment by SebastienDaniel** [comment]
Oh, I don't want to start a debate, I think we've all read plenty on the pros/cons of that question that generates flame more than anything. Above all, when enforcing a coding style, consistency is key and that's always what I'll go for.

If the brunt of the dev team opt for no-semicolons, I'll adapt and so should others. I'll not take this to religious extremes, I promise :)

**Comment by VictorW1** [comment]
Is there good documentation on the API? I'm not a nodejs developer, but I'd like to be able to hook into it from external apps. For example iOS and android apps that can do things like : sign up, forget password, make a topic, vote on a topic, etc when fired at the server. Good api documentation and a quick start guide would be amazing.

**Comment by asbjornenge** [comment]
Ref. @VictorW1's comment above. Maybe it's a good idea to have a cleaner separation between the APP and the API, both in documentation and code?

**Comment by gvilarino** [comment]
I agree with a cleaner separation on the docs; they're semi non-existing on the API (btw, you can check [our public docs here](https://docs.democracyos.org)).

I would argue, nonetheless, for the choice of keeping every module under `lib`: we like to keep our codebase organised as _modules_, where each module has its set of responsibilities -them being front end, back end or both- and is self-contained, exposing an API. This way not only code addition is simple (you want a new feature, code a new module) but also our modules become completely or partially reusable (just the front-end parts, all parts, just the styles, etc.). This also lays the ground for a (very desired) plugin architecture, or even breaking it all into microservices, in the future.

In my personal opinion, breaking the codebase into a `/site` and `/api` structures end up bringing more complexity than what's needed, especially when we want to be as succinct as possible.

That being said, hell yea for docs. I've been looking closely at stuff like [`Readme.io`](http://readme.io/), [`readthedocs`](https://readthedocs.org/) and [`apiary.io`](https://apiary.io/) recently to think about how this should happen. Thoughts?

**Comment by gvilarino** [comment]
What about something like [`stylelint.io`](http://stylelint.io/) for linting our `stylus` files?

**Comment by mjlescano** [comment]
Already [here](https://github.com/DemocracyOS/democracyos/blob/master/lib/build/css.js#L30-L33) :D
[`houndci.com`](houndci.com) doesn't implement it; but we could add `gulp css:lint` to travis.

**Comment by gvilarino** [comment]
Maybe [`publish-please`](https://github.com/inikulin/publish-please/) for releasing?

**Comment by bhack** [comment]
I think we need to evaluate how to easy setup a scalable microservice deployment. See the opensource initiative at https://dcos.io.  But node.js api for mesos seems not to be maintained anymore https://www.npmjs.com/package/mesos.

**Comment by bhack** [comment]
Also we will need a little bit of Machine learning at some point to scale on large depolyments. I don't think that we could solve all the issues of a collaborative politic scaling system with crowdsourcing (i.e. we will need clustering, collaborative filtering etc..). Using a micro service infrastructure could let to complement Democracyos with other micro services like Spark, elasticsearch etc.

**Comment by gvilarino** [comment]
Agree on that last part @bhack , though I think we'll need to see how this plays out on a large-enough scale in order to make proper decisions for ML.

Regarding microservices deployment, I think the way to go is `Docker Compose` + `Swarm` as it is extremely popular, community backed and very easy to learn, whereas `Mesos` is super strong although the learning curve and maintenance effort seems tougher.

**Comment by bhack** [comment]
Yes but in dcos flavour it is very easy

**Comment by gvilarino** [comment]
@mjlescano what about [`snyk.io`](https://snyk.io/blog/out-of-beta/)?

**Comment by gvilarino** [comment]
What about [`helmet`](https://github.com/helmetjs/helmet) for API security?

**Comment by gvilarino** [comment]
We can check [`sagui`](https://github.com/saguijs/sagui) for some additional inspiration on this matter

**Comment by franciclo** [comment]
Closing this, since we already take some of the technologies described here for coming versions. This discussion has been very useful, thank you all, surely we will be opening new discussions soon.
