### ISSUE TITLE
Bug : Youtube video sometimes disappear after topic is saved

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyOS/democracyos#1218]
Hey guys, 

Here is a description of the bug : 
I add a Youtube video on a topic, save it and load the topic's page. Sometimes it sticks but other times it just disappears. I usually check the admin topic edition but there is no trace of the video I added. I usually have to insert it several times.

I've reproduced this bug several times on different instances and version of DemocracyOS.

Do you have any idea from where this might come from?

**Comment by franciclo** [comment]
Not going to support youtube video embeds in the near future.
Closing this, since when we implement this again will be under hole new architecture.
