### ISSUE TITLE
Sort democracies on index page by popularity

### ISSUE THREAD

**Issue by williamcodes** [DemocracyOS/democracyos#1251]
I just visited the app for the first time and tried to find a democracyOS instance to check out. The top 5 are all empty. It looks like most of them are test accounts. This makes me less likely to participate.

As a User,
When I visit the democracies index page,
Then I would like to see the most active democracies on top

Comments:
Popularity could be determined by number of users subscribed to that democracy. Number of issues available for vote is a bad metric because one person could start many issues which each have no votes. Number of votes would be a great metric because it shows engagement. Caching might be needed at the democracy level because it might be slow to count every vote for every issue for every democracy.

**Comment by franciclo** [comment]
Totally agree, i also think we need to show more meta-data in the forum cards, like activity, participants, open topics.

**Comment by franciclo** [comment]
@peckjon also suggested this:

> Suggested fix: display the number of open/closed topics for each forum on the homepage. Add the ability to sort by each (plus 'recently active' etc).

**Comment by franciclo** [comment]
Closing since we are deprecating the democracies feed.
