### ISSUE TITLE
add a search bar for democracies

### ISSUE THREAD

**Issue by williamcodes** [DemocracyOS/democracyos#1252]
I tried to find a democracyOS instance for my city, but got tired of clicking `load more` only to be shown more test instances with no issues or votes in them. This discouraged me from engaging further. If I had a search bar, I could look for NYC, and if I didn't find it, I could make a new instance myself.

As a user,
When I am on the democracies index page,
Then I can search for democracies by name

Comments:
Search bars can get really complicated. Better to keep it simple in the beginning. It looks like this project uses bootstrap, and that comes with a search box, so at least the styling is taken care of. As for implementation, a simple query to the database that fuzzy searches by forum name would be enough. Eventually, a typeahead feature and an elasticsearch instance would be cool, but at this point probably not worth the time.

**Comment by mjlescano** [comment]
Totally agree with everything @williamcodes, we will be working on this some time in july :)
Nevertheless I'm closing this issue because it's duplicated: https://github.com/DemocracyOS/democracyos/issues/1193
