### ISSUE TITLE
Weird character being rendered on top of avatar in comments/replies

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#1262]
There's something like a bullet or `o` character there.

![image](https://cloud.githubusercontent.com/assets/2538465/16958304/581a090c-4db6-11e6-9b6a-8d1b75e79fac.png)

**Comment by gvilarino** [comment]
@mjlescano is this fixed? I don't see a linked commit.

**Comment by mjlescano** [comment]
Yup, because it was already fixed on `master`, but not deployed :shipit:
