### ISSUE TITLE
Improve new lines parsing on comments

### ISSUE THREAD

**Issue by 3rdwiki** [DemocracyOS/democracyos#1283]
Mark down is obvious.
http://daringfireball.net/projects/markdown/syntax

There needs to be a basic way for formatting to be implemented through the comments on various bills etc.
When I comment - all of my text get scrunched up into one big mess. So there needs to be a basic way to implement MarkDown - and tell the people how to do that !

Cheers,
great site.
democracy.im

**Comment by mjlescano** [comment]
Markdown is already implemented on comments! 😁

You can use MD directly on comments, and there's some info on how to use it on the "Formatting Help" on the right:
<img width="565" alt="screen shot 2016-08-19 at 13 47 44" src="https://cloud.githubusercontent.com/assets/558901/17819551/d72d884c-661e-11e6-8be3-044b1bc17ff4.png">
And that looks like this:
<img width="553" alt="screen shot 2016-08-19 at 15 05 49" src="https://cloud.githubusercontent.com/assets/558901/17819550/d72bdf38-661e-11e6-865b-6a725eb47e61.png">

But yeah, newlines are handled in a weird way. I'm converting this issue to a `bug` so we can take care of that :)
