### ISSUE TITLE
Add insecure connection warning

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#1285]
When the client renders, always perform a check on `location`. If it isn't local (i.e.: `localhost`, or similar) and the app isn't being served via `https`, display a warning indicating they're using an insecure version of DemocracyOS.

Optionally, we can provide a link to an explanation on `TLS` and secure connections, a page on our docs on security or something else.

**Comment by dkaoster** [comment]
Happy to try to take a stab at this one. What do you think is the best way to display the warning? Should we use one of the existing modal components or something else?

**Comment by gvilarino** [comment]
I guess that by adding something on top of [the header](https://github.com/DemocracyOS/democracyos/blob/master/lib/header/template.jade) should work well. Something noticeable through the whole screen, like those cookie warnings you get all the time nowadays.

I guess a link to a configurable URL would also help (it could default to our docs on TLS).

What do you think?

**Comment by mjlescano** [comment]
Merged, thanks @dkaoster 😊

**Comment by dkaoster** [comment]
@mjlescano you're welcome! 

One thing to note though (also for my future reference), when I added a string into en.json and not into all the other languages, is that something that needs to be flagged somewhere? What is the translation process for new strings?

**Comment by mjlescano** [comment]
Nope, nothing breaks, the only needed language for something to be mergeable is english. All the other languages will use the `en` key if it's missing.

Then, to work with translation files, there's the `./bin/dos-translate` command line utility, that let you list missing keys, sort files, and some other niceties :)
