### ISSUE TITLE
Please, do a release for 1.4.1 that includes 7389a5c

### ISSUE THREAD

**Issue by ghostbar** [DemocracyOS/democracyos#1299]
1.4.0 is completely unusable, because it misses this fix https://github.com/DemocracyOS/democracyos/commit/7389a5c31b70fba2a1315d3d48689324f9a84337

**Comment by mjlescano** [comment]
Thanks for the heads up! I missed this one ... 👉 [1.4.1](https://github.com/DemocracyOS/democracyos/releases/tag/1.4.1)
