### ISSUE TITLE
Application returning "This page does not exist"

### ISSUE THREAD

**Issue by danakim** [DemocracyOS/democracyos#1311]
Hi,

I am trying to install DemocracyOS on a personal server, running Debian. I have tried both the latest version (1.4.4), an older version (1.3.0) and the Docker container. The application builds and starts fine, the logs look rather clean, it successfully connects to MongoDB, I can connect to its port (3000) in a browser.

But when I do that, I get a 404 error page saying "This page does not exist". I get the same error no matter what page I try (/, /signin, /signup, etc). I have attached a screenshot with how the error looks like.

OS: Debian 8.5
NodeJS: 4.6.0
MongoDB: 3.2.9

Not sure what am I missing :( Can someone please advise?

Thanks!

![screen shot 2016-09-29 at 12 24 05](https://cloud.githubusercontent.com/assets/1060347/18948840/643038a6-8641-11e6-81ff-f1ed4eeb08d9.png)

**Comment by mjlescano** [comment]
There was a bug on the build, it's already fixed on `1.4.5` :D

**Comment by danakim** [comment]
Hi Matías,

Sorry, but 1.4.5 hasn't fixed my issue :( I have also tried an older version (1.3.0). I still have the same "This page does not exist" error. To give you a bit more detail, this is how the startup of the application looks like:

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
  democracyos:db Using mongodb hosts: localhost:27017 +248ms
  democracyos:db Using mongodb URI: mongodb://localhost:27017/DemocracyOS-development +0ms
  democracyos:db Connecting to MongoDB database DemocracyOS-development +1ms
  democracyos:server About to start embedded notifier notifier with options: {"mongoUrl":"mongodb://localhost/DemocracyOS-development","organizationName":"The DemocracyOS Team","organizationEmail":"no-reply@democracyos.org","mailer":{"name":"The DemocracyOS Team","email":"no-reply@democracyos.org","service":"","auth":{"user":"","pass":""}}} +1s
  democracyos:notifier:transports Initializing nodemailer API client +9ms
  democracyos:server Server started at port 3000. +4ms
  democracyos:db Connected to MongoDB on URI: mongodb://localhost:27017/DemocracyOS-development +26ms
  democracyos:db Connection to MongoDB is now OPEN on URI: mongodb://localhost:27017/DemocracyOS-development +6ms
  democracyos:notifier agenda initialized. +65ms
  democracyos:server Embedded notifications service started +101ms
  democracyos:root DemocracyOS server running... +0ms

As you can see there is a js-bson error. Could that be the problem? Then, whey I do a request to the root of the app (/), this is how it looks like the logs:

  democracyos:jwt HTTP header x-access-token has no token. Moving on... +59s
  democracyos:l10n Inferring user locale from HTTP header accept-language: en-US,en;q=0.8,ro;q=0.6 +0ms
  democracyos:l10n Setting locale: en +1ms

I really do not see any issues, I don't get it why it could be serving me that "page not found". Could it be that I am missing something in the config maybe?

Thanks,
Dan

**Comment by mjlescano** [comment]
Hi Dan!
Nope, the BSON stuff is not the problem. What does the command `npm run build` prints?

**Comment by danakim** [comment]
Hi Matías,

First of all, thanks for helping me with this! `npm run build` prints:

[dan@host:~/democracyos-1.4.5]$ npm run build

> democracyos@1.4.5 build /home/dan/democracyos-1.4.5
> gulp build

[13:16:17] Using gulpfile ~/democracyos-1.4.5/gulpfile.js
[13:16:17] Starting 'js:build'...
[13:16:17] Starting 'css:build'...
[13:16:17] Starting 'public'...
[13:16:17] Finished 'js:build' after 72 ms
[13:16:17] Finished 'css:build' after 36 ms
[13:16:17] Finished 'public' after 15 ms
[13:16:17] Starting 'assets'...
[13:16:37] Finished 'assets' after 20 s
[13:16:37] Starting 'build'...
[13:16:37] Finished 'build' after 10 μs

Let me also give you my `development.json` config file: https://gist.github.com/danakim/8df30b280b05b8466f6adec849515c88

I have followed the instructions from here: http://docs.democracyos.org/install.html

Thanks,
Dan

**Comment by danakim** [comment]
Hi Matías,

Sorry to push for this, but do you have any ideas on how to fix this? I need to install DemocracyOS by the end of the week, as it will be used in a project teaching high school teenagers about the democratic process :) This project is done by a NGO, all pro-bono so we try to only use open source software and DemocracyOS seemed like a great fit for what we want to do. Unfortunately, I can not use it :(

Could it be because I am using Node 4.6.0. Should I use 6.7 ?

Thanks,
Dan

**Comment by mjlescano** [comment]
Hi!
Do you have a public URL? or what does the browser console prints?

Also, let's move the conversation to our [Gitter Channel](gitter.im/DemocracyOS/democracyos), so we can talk more fluently and more people can help :)

**Comment by danakim** [comment]
Hi,

No - I do not have one yet. But I did find out what was the problem. Now I would need help with something else. Let's talk on the gitter channel.
