### ISSUE TITLE
Dead link in documentation page

### ISSUE THREAD

**Issue by PierreMesure** [DemocracyOS/democracyos#1316]
Small problem here, a link is dead on this [page](http://docs.democracyos.org).

> Or if you want to go a little further, fix it on _**github.com/DemocracyOS/app/docs**_ and send a Pull Request.

I wasn't sure which link you wanted to replace it with so I didn't try to fix it myself.

**Comment by franciclo** [comment]
thanks, i think it should point to https://github.com/DemocracyOS/democracyos/tree/master/docs
I will take a look at it later.

**Comment by Qeole** [comment]
Not sure if directly related, there are also several dead links on [this page](http://democracyos.eu/docs-fr/) (not the same as above). I found the three links below (in bold text):

> Ou, si vous souhaitez aller un peu plus moi, la corriger sur **github.com/DemocracyOS/app/docs** et envoyer un **Pull Request**.

> Vous pouvez commencer par **Installer DemocracyOS** sur votre machine.

**Comment by franciclo** [comment]
First issue has been resolved but the second correspong to another Github Organization, our friends in France, https://github.com/democracy-os-fr
