### ISSUE TITLE
SSO support?

### ISSUE THREAD

**Issue by leog** [DemocracyOS/democracyos#1331]
Hello there!

I was wondering if there is any chance to use SSO with a service like Auth0.

Part of our intention to use DemocracyOS is to be able to get users log in through Auth0 among other web apps that conforms our platform.

Thanks a lot in advance.

**Comment by m3talsmith** [comment]
👍  I think SSO via OAuth2 should be a given these days; as an option of course.

**Comment by LucianDavies** [comment]
@m3talsmith when you say as an Option you mean an addition to the local passport strategy cause at first glimpse at the code, I figure we could replace the auth-facebook with Auth0 which if done properly would not change the setting up of an instance much.

**Comment by LucianDavies** [comment]
@leog @m3talsmith finished a mock up of this but just noticed that there is no client-side testing. I basically swapped out the facebookbook login for auth0. Simple sign-in and logout works but also just noticed that the frontend is migrating to react. @leog I could help migrate to auth0 if you want

**Comment by leog** [comment]
@LucianDavies thanks for working on this! let me know which are the steps and I can switch facebook auth to auth0. I have an instance on Heroku to test it out.

**Comment by mjlescano** [comment]
Hi! Sorry for the delay responding here; Do you want to show me where are you trying it? maybe I can give you some tips.

And also yes, we're really close to merge the branch `add-react`, that implements React on all the public content (which is at `/lib/site`)

**Comment by LucianDavies** [comment]
@leog wants to add auth0 to the non react branch...  with bare minimum changes these are the files you would have to modify:
  
        modified:   config/defaults.json
	modified:   lib/layout/index.jade
	modified:   lib/models/user.js
	modified:   lib/site/auth-facebook/auth-facebook.js
	modified:   lib/site/auth-facebook/form.js
	modified:   lib/site/auth-facebook/routes.js
	modified:   lib/site/auth-facebook/strategy.js
	modified:   lib/site/layout/index.jade

if @mjlescano allows I could do a pull request to DemocracyOS and then you can pull it from there otherwise I am just gonna push it to my own fork.. they seem to be focused on adding the react branch so it may take a bit to review the code if we do the pull request approach.

**Comment by mjlescano** [comment]
Sorry for the long response time, and yes! totally up for adding Auth0 as alternative.

Moving the discussion to #1412
