### ISSUE TITLE
Increase minimum password length.

### ISSUE THREAD

**Issue by EdOverflow** [DemocracyOS/democracyos#1343]
Currently you require a minimum password length of **6** characters. I would highly recommend increasing the minimum requirement to **8**.

NIST also recommends a minimum of 8 characters: https://pages.nist.gov/800-63-3/sp800-63b.html#memorized-secret-verifiers

> Verifiers SHALL require subscriber-chosen memorized secrets to be at least 8 characters in length.

---

~~~
input.form-control(type='password', name='password', tabindex=2, placeholder=t(''), value='', validate='required min-length:6')
~~~

Link to password settings: https://github.com/DemocracyOS/democracyos/blob/master/lib/settings/settings-password/template.jade#L14

~~~
input.form-control(type='password', name='password', tabindex=1, placeholder=t('password'), validate='required min-length:6')
~~~

Link to reset form: https://github.com/DemocracyOS/democracyos/blob/master/lib/site/forgot/reset-form.jade#L12

~~~
input.form-control(type='password', name='password', tabindex=4, placeholder=t('password'), validate='required min-length:6')
~~~

Link to password signup form: https://github.com/DemocracyOS/democracyos/blob/master/lib/site/signup/signup-form.jade#L22

**Comment by franciclo** [comment]
Thanks for the detailed explanation, we will consider this.

**Comment by mjlescano** [comment]
I like it!

**Comment by franciclo** [comment]
We have take this into account and will apply it in next major release we are currently working on.
