### ISSUE TITLE
Email for admin not appearing in deploy to Heroku

### ISSUE THREAD

**Issue by carlvlewis** [DemocracyOS/democracyos#1371]
When deploying to Heroku, upon initial app preview, the email entered in the  `*STAFF` email field in deployment config settings is not being recognized as a user for the deployed app.

So, in essence, I have no admin privileges. Ideas?

**Comment by mjlescano** [comment]
@carlvlewis make sure that you entered the value correctly. On the Settings section of your Heroku App, if you edit `STAFF` it should look something like this:

<img width="583" alt="screen shot 2017-02-20 at 20 18 07" src="https://cloud.githubusercontent.com/assets/558901/23144983/0bfd7290-f7aa-11e6-82d3-e562e8a1a075.png">

Also, don't forget that you still have to register with that email :)
