### ISSUE TITLE
[Docs] Add documentation for translations

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#1373]
It should describe how translations are structure, how `bin/dos-translation` works, and how to add new languages to DOS.

**Comment by mjlescano** [comment]
Starting point on adding new languages:
* Locale files are located [here](https://github.com/DemocracyOS/democracyos/tree/master/lib/translations/lib)
* [here](https://github.com/DemocracyOS/democracyos/blob/master/config/defaults.json#L123) are located all available translations.
* [`bin/dos-translate`](https://github.com/DemocracyOS/democracyos/blob/master/bin/dos-translate) helps a lot, and it's explained [here](https://github.com/DemocracyOS/democracyos/wiki/Translate-Tool).

**Comment by franciclo** [comment]
We are currently not maintaining this script and is going to be deprecated in the future.
