### ISSUE TITLE
Add SSL on democracyos.org

### ISSUE THREAD

**Issue by reggi** [DemocracyOS/democracyos#1380]
Seems that HTTPS is not working for the following domain:

https://democracyos.org

<img width="324" alt="screen shot 2017-03-17 at 12 43 53 pm" src="https://cloud.githubusercontent.com/assets/296798/24053421/669ed9d2-0b0f-11e7-9d02-47a6fe1725c5.png">

**Comment by mjlescano** [comment]
Yup, we have the static page deployed on GitHub pages, which by default does not allows SSL for custom domains, more info: https://github.com/isaacs/github/issues/156

We should configure CloudFlare or a similar service for the domain, as explained here: https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

As a note, this only applies to the base domain democracyos.org, but for example https://app.democracyos.org/ it's already correctly configured.

**Comment by mjlescano** [comment]
@gvilarino just assigned you, because you're the domains admin :shipit:

**Comment by gvilarino** [comment]
@mjlescano should we go ahead with the cloudflare setup then?

**Comment by mjlescano** [comment]
Yup please, Github's still without SSL...

**Comment by franciclo** [comment]
Wont move to cloudflare in the future and we are cool with the static product site to be hosted on GH pages for now
