### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by solanoepalacio** [DemocracyOS/democracyos#1385]
Hi,
We are going to implement a search feature functionality.

## User interface
It will be made as a react component so it can be placed on any page, but to start we will attach it to the homepage.
The search will query the database and bring results filtered by forums, topics, and tags. The user will have the possibility to switch between them.
The homepage will keep the structure it has until a new search is triggered; in that moment the forum-cards container would disappear to give place to a list of search results.
Results will be ordered according to the type in a github-wise way (a horizontal bar at the top will have the list of types to filter from).
We will leave space to add a 'sorting' and a natural text processing feature in the future. Also, it would be nice to use 'wilson-score' library to evaluate the relevance of the search results.

## Endpoints
TBD.

## Search methods
On a first version, the api will query the database through the db-api already implemented.
On later versions, we will try to include more advanced search methods like elastic-search, solr, etc...

**Comment by mjlescano** [comment]
Worth mentioning, you're working it on https://github.com/Plataforma5/democracyos :)

**Comment by solanoepalacio** [comment]
We've been researching about different ways to implement the full-text search to upgrade the search feature we started last week. It came down to two options. One is setting Solr in a JVM and the other one is to implement an algorithm of our own. Both have pros and cons. Solr needs a standalone server to run, which adds a complexity layer to people who might want to use democracyos but doesn't have that much experience in app development. But it's quite fast, stable and its configurations can easily scale along democracyos as it grows. On the other hand, making an implementation of an algorithm of our own to search will be simpler and reduce overhead, but it might be a bit slower, harder to scale, and consume more resources. Any opinions on the matter?

**Comment by franciclo** [comment]
Hey, good job!
We should look first for fulltext solutions within the node js ecosystem.
Adding a new backend service will require more complexity as you point out and more skills from people installing DOS, and we like to keep it simple.

**Comment by mjlescano** [comment]
Conversation for reference: https://gitter.im/DemocracyOS/democracyos?at=58e399df68bee3091f0beafa

**Comment by franciclo** [comment]
we are deprecating multiforum functionality, will add search for topics in the future and apply some work developed here, thanks.
