### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by emanuelstanciu** [DemocracyOS/democracyos#1392]
Hello,

After configuring the platform I was able to consistently use the website and everything was working, but a new session would result in a browser error: "too many redirects"
After I logged off the user that was working, I got the same on my active session.
Tried restarting the server a few times and it starts fine, but all logs look like this:

`  democracyos:jwt HTTP header x-access-token has no token. Moving on... +3ms
  democracyos:l10n Inferring user locale from HTTP header accept-language: en-US,en;q=0.8,en-GB;q=0.6,ro;q=0.4 +0ms
  democracyos:l10n Setting locale: en +1ms
  democracyos:jwt HTTP header x-access-token has no token. Moving on... +3ms
  democracyos:l10n Inferring user locale from HTTP header accept-language: en-US,en;q=0.8,en-GB;q=0.6,ro;q=0.4 +0ms
  democracyos:l10n Setting locale: en +0ms
  democracyos:jwt HTTP header x-access-token has no token. Moving on... +4ms
  democracyos:l10n Inferring user locale from HTTP header accept-language: en-US,en;q=0.8,en-GB;q=0.6,ro;q=0.4 +0ms`

What's happening with it? Any help is greatly appreciated. Thanks.

**Comment by emanuelstanciu** [comment]
I by-passed this with a fresh pull on a new machine.. not sure what was wrong in the end.. I'll close it for now

**Comment by emanuelstanciu** [comment]
I managed to replicate this behavior. It's generated by the visibility setting in the config file. If you set the platform to hidden, it will retain all logged-in sessions, but any new not-logged-in user who is hitting the site get's the "too many redirects" error from the browser.
Is this intended?

**Comment by mjlescano** [comment]
Hi @emanuelstanciu ! I'm reviewing the error :)

Just as a note, you can now configure the visibility on the admin, without having to use the global (and legacy) `"visibility"` configuration. In your server, just go to `/admin/permissions`
