### ISSUE TITLE
Publish action stops the server

### ISSUE THREAD

**Issue by emanuelstanciu** [DemocracyOS/democracyos#1393]
I have latest 2.2.2 and when I publish a topic it fails the entire server. Here's the stack:

` democracyos:topic publish topic 58f9eb76fa1ac305d89a5dd6 at Fri Apr 21 2017 12:18:23 GMT+0000 (UTC) +8ms
  democracyos:db-api:notification Attempting to push new notification: undefined +4ms
  democracyos:db-api:notification Notification pushed succesfully +8ms
  democracyos:topic Successfully notified publishing of topic 58f9eb76fa1ac305d89a5dd6 +0ms
  democracyos:notifier Job 'topic-published' started +5ms
the options [authMechanism] is not supported
  democracyos:notifier Job 'topic-published' completed - duration: 17 +18ms
  democracyos:notifier Job 'update-feed' started +10ms
the options [authMechanism] is not supported

/root/democracyos/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^
callback already called - job topic-published already marked complete

npm ERR! Linux 4.4.44-1-pve
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! democracyos@2.2.2 start: `NODE_PATH=. node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the democracyos@2.2.2 start script 'NODE_PATH=. node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the democracyos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_PATH=. node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs democracyos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls democracyos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/democracyos/npm-debug.log
Makefile:14: recipe for target 'run' failed
make: *** [run] Error 1`

**Comment by mjlescano** [comment]
Hi! Which OS/server are you using?

**Comment by emanuelstanciu** [comment]
hi @mjlescano ,

I'm using ubuntu server 16.04 x64

**Comment by mjlescano** [comment]
Just been able to reproduce it! I'm working on a fix :)

**Comment by emanuelstanciu** [comment]
Great, thanks

**Comment by mjlescano** [comment]
Done! You should update to `2.2.3` and don't forget to re-run `npm install` :)

It was an error with DemocracyOS/notifier, fixed here: https://github.com/DemocracyOS/notifier/commit/8486c75c5f78d4c9c860036ca9f3235bfa4f74b8

Let me know if it works ok for you, and thanks for reporting it @emanuelstanciu !

**Comment by emanuelstanciu** [comment]
Works fine, thanks @mjlescano
