### ISSUE TITLE
/admin/users is blank

### ISSUE THREAD

**Issue by emanuelstanciu** [DemocracyOS/democracyos#1394]
I have enabled whitelisting in configuration and a new section has appeared: Enabled users
However, this is blank and I cannot add whitelisted users/domain(preferably)
![sketch](https://cloud.githubusercontent.com/assets/2768779/25346244/fd10ccc8-290e-11e7-9f11-2d532a722d87.png)

**Comment by mjlescano** [comment]
Thanks for reporting it @emanuelstanciu ! Just pushed a fix to `master`.
