### ISSUE TITLE
Login button and options should appear in the same screen

### ISSUE THREAD

**Issue by Annagramma** [DemocracyOS/democracyos#1399]
During login all the options should appear in the same screen, without scrolling down, regardless the resolution or screen size.

![image](https://cloud.githubusercontent.com/assets/4205060/25452891/8e8e370a-2a9d-11e7-8dec-25cf43bf1988.png)

**Comment by mjlescano** [comment]
This depends on your own screen, and only happens when facebook login is activated. Not going to fix.
