### ISSUE TITLE
Could we show replies by default?

### ISSUE THREAD

**Issue by Annagramma** [DemocracyOS/democracyos#1403]
![image](https://cloud.githubusercontent.com/assets/4205060/25455009/c02c310c-2aa4-11e7-9f73-3cf7ad34ff88.png)

**Comment by mjlescano** [comment]
I don't like it, because we don't have any way to defined which are the more important replies to show (because replies are not vatable). We could only show, for example, the most recent 1~3 replies.

**Comment by franciclo** [comment]
we will take this into account when building next version comments
