### ISSUE TITLE
Defaults.json file and environment variables

### ISSUE THREAD

**Issue by ogdabou** [DemocracyOS/democracyos#1425]
Hi !

**What I want to achieve ?**
- [DemocracyOS standalone stack](https://git.cm-cloud.fr/Politicus/politicus-rancher-catalog/tree/master/templates/DemocracyOs), deployable easily through a `rancher-catalog`, configurable via the `Rancher server interface`. People using rancher to manage their servers would be able to install democracyOS in a heroku-like way, except it's on their own servers.
- Plug and play, you start the stack, it works, you upgrade and you can rollback if it fails, etc ...
- Speak with you, speak with rancher and later on make an official `rancher-catalog entry` for democracyos

**Why I cannot achieve that ?**

Deploying with [this docker-compose.yml](https://git.cm-cloud.fr/Politicus/politicus-rancher-catalog/blob/master/templates/DemocracyOs/0/docker-compose.yml).   
*Ps: If you read this and use Rancher, feel free to use this catalog, democracyOS is awesome :). But for the moment you need to set a CONFIG_PATH env variable to a defaults.json file on your host server*

Here is the error I get
```
08/06/2017 18:47:49Error: /usr/src/config/defaults.json file not found.
08/06/2017 18:47:49    at loadConfig (/usr/src/node_modules/democracyos-config/index.js:48:11)
08/06/2017 18:47:49    at Object.<anonymous> (/usr/src/lib/config/index.js:10:14)
08/06/2017 18:47:49    at Module._compile (module.js:570:32)
08/06/2017 18:47:49    at Object.Module._extensions..js (module.js:579:10)
08/06/2017 18:47:49    at Module.load (module.js:487:32)
08/06/2017 18:47:49    at tryModuleLoad (module.js:446:12)
08/06/2017 18:47:49    at Function.Module._load (module.js:438:3)
08/06/2017 18:47:49    at Module.require (module.js:497:17)
08/06/2017 18:47:49    at require (internal/module.js:20:19)
08/06/2017 18:47:49    at Object.<anonymous> (/usr/src/index.js:2:16)
08/06/2017 18:48:03/usr/src/node_modules/democracyos-config/index.js:48
08/06/2017 18:48:03    throw new Error(options.defaultsPath + ' file not found.')
08/06/2017 18:48:03    ^
```

This is suprising because if no `defaults.json` is provided the application will fail regardless of env variables.  
In the documentation, I read

> These settings can be defined either as a JSON file (as described in the Environments and config files wiki page) following the config/defaults.json, or through environment variables.  

But the `.dockerignore`file includes a `config/*.json`directive.

**Is there any reason behind the fact DemocracyOS won't start without a defaults.json ?**

I (humbly) think this is due to the act you don't want someone to put in production a democracyos not configured. 

**If that is so, would you consider ?**  
- Replace `defaults.json` by `defaults.js`
- Write default configuration file using [common-env](https://www.npmjs.com/package/common-env)
   - `getOrEsleAll` method for facultative values (that can pass into production without modifications)
   - `getOrDie` method for each variable we must set

This way, you can still provide a custom `defaults.js` using hardcoded values in production, or override theses values with environment variables. And  if requirements are not met users will have error messages saying `SET [variable_name] environment variable`.  
And more importantly **to me at least :)** be able to run DemocracyOS in the cloud without setting up a configuration container or the host server.

Thank you reading all this, thank you for you work <3.

**Comment by mjlescano** [comment]
Hi @ogdabou! Thanks for the thorough explanation 😊

That's weird, how are you building the Docker image?

The file `config/defaults.json` should exist on the Docker image, because the `.dockerignore` says:
```
config/*.json
!config/defaults.json # This avoids ignoring defaults.json
```

And running the latest image, it has the file:
```
$ docker run --name dos --rm -it democracyos/democracyos:latest ls -la /usr/src/config
-rw-r--r-- 1 root root   22 May 25 23:03 .gitignore
-rw-r--r-- 1 root root 3260 May 25 23:03 defaults.json
```

**Comment by mjlescano** [comment]
Closing this until we're sure theres a bug
