### ISSUE TITLE
Renew Security Certificate

### ISSUE THREAD

**Issue by HussienH** [DemocracyOS/democracyos#1427]
![untitled](https://user-images.githubusercontent.com/29569040/27326746-0674fc58-55b5-11e7-92e9-5235ab8a8956.jpg)

we should renew the certificate

app.democracyos.org uses an invalid security certificate. The certificate expired on June 16, 2017 at 2:59 AM. The current time is June 20, 2017 at 12:33 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by mjlescano** [comment]
Hi @HussienH ! Sorry for this, it's already fixed. It should be refreshing as soon as the DNS does.
