### ISSUE TITLE
Private democracies completely disappear from the list of democracies

### ISSUE THREAD

**Issue by ashkang** [DemocracyOS/democracyos#1441]
Private democracies completely disappear from the list of democracies even when user is signed in. Is this intentional behavior or a bug? Looks like a bug to me.

**Comment by mjlescano** [comment]
Yup! If you want it to be "listed", the Democracy should be "Restricted" instead of "Private"

**Comment by ashkang** [comment]
@mjlescano But then it would be visible to the public. What we're looking for here is a private democracy (Not visible to general public).

**Comment by ashkang** [comment]
@mjlescano I still don't get the point of completely removing a democracy from the list even from the view point of people that are participants/moderators/admins/etc. It makes total sense to remove it from other people that are not part of that democracy, but current behavior is extremely confusing IMHO.
