### ISSUE TITLE
Define local SMTP

### ISSUE THREAD

**Issue by willouuu** [DemocracyOS/democracyos#1442]
Hi 
We want to use DemocracyOs internally
We want to use our SMTP server, our regulations prohibit the use of external providers.
How can we configure it?

Thanks

**Comment by mjlescano** [comment]
Hi @willouuu !

You can use the `mailer.nodemailer` configuration, as described here: http://docs.democracyos.org/configuration.html#-notifications-nodemailer-

For example, our mailtrap smtp config on `produciton.json` is something like this:
```
{
  "notifications": {
    "nodemailer": {
      "host": "mailtrap.io",
      "port": 2525,
      "auth": {
        "user": "username",
        "pass": "the-password"
      }
    }
  }
}
```

And, if you want to configure it with environment variables, it would be like this:
```
NOTIFICATIONS_NODEMAILER='{ "host": "mailtrap.io", "port": 2525, "auth": { "user": "username", "pass": "the-password" } }'
```

**Comment by willouuu** [comment]
Thank you very much !
You should put this example in the documentation.
We do not understand that we must put these instructions in the variable NOTIFICATIONS_NODEMAILER

**Comment by willouuu** [comment]
Hi, 
Sorry
To latest version (2.9.3), not receveid new topic notification in single forum mode (but 2.8.1 it's work )
King regards
