### ISSUE TITLE
Topic Form - Date Picker broken layout

### ISSUE THREAD

**Issue by vickyguareschi** [DemocracyOS/democracyos#1445]
If you click on the date picker to choose a closing date and save without closing the calendar, it sticks to the top left corner of the window when it should disappear. 

![bug](https://user-images.githubusercontent.com/10161930/28790180-703d4974-75fe-11e7-8dae-08add66a009e.jpeg)

Browser: Chrome 57.0.2987.133 (64bit)

**Comment by mjlescano** [comment]
@vickyguareschi drag the screen to the issue please, so it is visible to everyone.

**Comment by vickyguareschi** [comment]
@mjlescano Done.

**Comment by franciclo** [comment]
closing since we are rebuilding this section in next version.
