### ISSUE TITLE
Heroku Deploy doesn't work

### ISSUE THREAD

**Issue by rdgutierrez** [DemocracyOS/democracyos#1447]
I deploy using the heroku button, the app was running, and i sign up, but doesn't work the login and now i get a blank screen at https://ciudadano-activo.herokuapp.com/signin

**Comment by ExWasimV** [comment]
Same problem. did you find a solution ever?

**Comment by franciclo** [comment]
this issue was due an empty mailer configuration, it has been resolved adding a default mailer config in the notifier module.
