### ISSUE TITLE
Remove account on app.democracyos.org

### ISSUE THREAD

**Issue by petrk94** [DemocracyOS/democracyos#1458]
Hello, 
I would like to know how to get removed my account  on app.democracyos.org?

Cant find any option for this in the settings.

Thanks

**Comment by franciclo** [comment]
Account deleting is not possible in the demo page, sorry. we will remove that instance and all its data soon.

**Comment by ZerooCool** [comment]
I have make this tutorial, in french, for DemocracyOS and MongoDB with Docker.

But, 
1- SSL warning.
2- Mail don't send.
I'm looking for.

**Comment by petrk94** [comment]
@ZerooCool I think you are in the wrong issue thread?
He was the clarification about whether accounts on the demo website can be deleted
