### ISSUE TITLE
TypeError: Cannot set property 'mailer' of undefined

### ISSUE THREAD

**Issue by mariomenjr** [DemocracyOS/democracyos#1467]
While trying to complete installation of DemocracyOS I faced the following issue:

![image](https://user-images.githubusercontent.com/1946936/32421628-633a1552-c24f-11e7-8402-34273ff3f55a.png)

Also, as suggested in the error output I have included the log.
[npm-debug.log](https://github.com/DemocracyOS/democracyos/files/1444674/npm-debug.log)

**Comment by dimitriskr** [comment]
Is there any update on this one? I'm facing the same issue too

**Comment by deivid-rodriguez** [comment]
I was getting the same error yesterday when setting up a development environment.

This change seemed to do the trick:

```diff
diff --git a/config/defaults.json b/config/defaults.json
index 82dc5856..b47a76b2 100644
--- a/config/defaults.json
+++ b/config/defaults.json
@@ -44,7 +44,7 @@
     "mailer": {
       "name": "The DemocracyOS Team",
       "email": "no-reply@democracyos.org",
-      "service": "",
+      "service": "mailer",
       "auth": {
         "user": "",
         "pass": ""
```

**Comment by dimitriskr** [comment]
I can confirm this patch works. Thanks a lot David!

**Comment by deivid-rodriguez** [comment]
You are welcome! :)

**Comment by franciclo** [comment]
fixed default mailer in democracyos-notifier repo, a temporary fix will be as deivid puts it, specifying a default mailer config.
