### ISSUE TITLE
Download a DemocracyOS virtual machine

### ISSUE THREAD

**Issue by ZerooCool** [DemocracyOS/democracyos#1468]
I am currently looking for a link, to download a virtual machine from Democraty Os, for Virtualbox, on Debian / Ubuntu ?

**Comment by mjlescano** [comment]
Hi @ZerooCool ! We don't have an official VM for VirtualBox, we always use the Docker image to resolve virtualization.

If you need it running on VirtualBox for an specific use-case, take a look at the repo https://github.com/DemocracyOS/onpremises, which is configured to setup any machine using Ansible (via ssh) to run DemocracyOS. You could use it to setup a VirtualBox VM.

**Comment by ZerooCool** [comment]
Hello, what is the good way for use the docker image to resolve virtualization ?

I test with my wiki
https://www.visionduweb.eu/wiki/index.php?title=Installer_DemocracyOS
Can you read my wiki and give help, for step 7.1, 8, 8.1 please ?

3.1.1) Install Ansible Ok ?
3.1.3.2.2) Clone Nginx Ok ?
5) Create a Droplet DigitalOcean Ok !

7.1) i don't know how i can configure ansible with file : hosts, inventory, playbook.yml  (Not Ok)
8) then, i don't know how i a can create playbook.yml and use it. (Not Ok)

8.1) I have not test this commande ( I need install docker ? ) (Not Ok)
docker pull democracyos/democracyos:latest && docker-compose -f /usr/src/docker-compose.yml restart -d
