### ISSUE TITLE
Tutorial onpremises - The last link not work

### ISSUE THREAD

**Issue by ZerooCool** [DemocracyOS/democracyos#1469]
https://github.com/DemocracyOS/onpremises

**MongoDB Backups**

If you're running on staging or production environment, everyday at 23:59 a dump of the entire database will be saved to /usr/src/backups. You can check the file templates/backup.js to see what it does.

_templates/backup.js <-- This link not work_

**Comment by franciclo** [comment]
thanks it should be .j2 not .js, it fixed now
