### ISSUE TITLE
Default installation deploys mostly blank?

### ISSUE THREAD

**Issue by ExWasimV** [DemocracyOS/democracyos#1473]
here is my deployment: https://citizengov.herokuapp.com

I can get one topic to load: https://citizengov.herokuapp.com/topic/5a467ec36b4fc700041a23c8

but not that homepage.

 I can't tell the difference because I am new to this entirely (I'm only going to be learning javascript this semester for the first time) but I still want to get a generic, default instance of this open source software running

**Comment by franciclo** [comment]
Closing since its repeated from #1447
