### ISSUE TITLE
Onpremises and ansible

### ISSUE THREAD

**Issue by ZerooCool** [DemocracyOS/democracyos#1476]
I seach how i can create : hosts, inventory, playbook.yml

I don't no how i can configure my client, with ansible. Look my wiki, un french, please.
https://www.visionduweb.eu/wiki/index.php?title=Installer_DemocracyOS#Reprendre_sur_la_Machine_Virtuelle

**Comment by franciclo** [comment]
closing here since its repeated from https://github.com/matiasdecarli/democracyos_onpremises/issues/1
i will try to get support into that issue
