### ISSUE TITLE
MongoError: connect ECONNREFUSED 127.0.0.1:27017 and Docker democracyos/democracyos

### ISSUE THREAD

**Issue by ZerooCool** [DemocracyOS/democracyos#1478]
# Installer MongoDB with Debian 9 Stretch.
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
sudo apt-get update
sudo apt-get install mongodb

sudo systemctl enable mongodb.service
sudo service mongodb start
systemctl status mongodb

# Docker
docker pull democracyos/democracyos
docker run --name demos -p 3000:3000 democracyos/democracyos

# Then, i have this error : 
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined
events.js:160
     throw er; // Unhandled 'error' event
     ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
   at Pool.<anonymous> (/usr/src/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:328:35)
   at emitOne (events.js:96:13)
   at Pool.emit (events.js:188:7)
   at Connection.<anonymous> (/usr/src/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:280:12)
   at Connection.g (events.js:292:16)
   at emitTwo (events.js:106:13)
   at Connection.emit (events.js:191:7)
   at Socket.<anonymous> (/usr/src/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:177:49)
   at Socket.g (events.js:292:16)
   at emitOne (events.js:96:13)
   at Socket.emit (events.js:188:7)
   at emitErrorNT (net.js:1281:8)
   at _combinedTickCallback (internal/process/next_tick.js:80:11)
   at process._tickCallback (internal/process/next_tick.js:104:9)

https://www.visionduweb.eu/wiki/index.php?title=Ajouter_Docker_sur_GNU_Linux#Installer_une_image_Docker_democracyos

**Comment by clauded** [comment]
I have the same problem but I'm using a mongo docker instance : in config/defaults.json mongoUrl  witch has a value of mongodb://localhost/... should be mongodb://mongo/... so it could connect to an external mongo instance.

**Comment by ZerooCool** [comment]
I do not actually know mongo DB, if you know how to use it, if you have a tutorial to use it with democracyos, thank you for sharing.

**Comment by clauded** [comment]
Here's how to do it:

### pull mongo 3.2 and democracyos docker image
docker pull mongo:3.2
docker pull democracyos/democracyos
### create mongo instance
docker run --name mongo -d mongo:3.2
### pre-create the democracyos instance volume
docker volume create democracyos1
### create democracyos instance linked to mongo instance and expose the config directory of democracyos
docker run -it --link mongo:mongo -e STAFF="adminuser@amail.com" --name democracyos1 -p 3000:3000 -v democracyos1:/usr/src/config -d democracyos/democracyos
### replace localhost with mongo in the connection string
sudo sed -i -e 's|localhost|mongo|' $(docker inspect democracyos1|grep Source| awk -F '"' '{print $4}')/defaults.json
### restart democracyos instance (it should not be running anyway)
docker restart democracyos1
### check that mongo and democracyos instances are running
docker ps

**Comment by ZerooCool** [comment]
Thank you for having detailed your way.
I will test as soon as possible.
Another huge thank you.

**Comment by ZerooCool** [comment]
Tank you i have test your very good tutorial, so easy, now, i can use a docker image with MongoDB and DemocracyOS.

I have this text, in red color, if you have the same best practice, step by step, i translate that in french.

Warning: You are using an insecure version of DemocracyOS. See the docs for details on implementing SSL.

How use it with SSL. I search and test that, ASAP.

**Comment by franciclo** [comment]
Hi, great tutorial @clauded im glad is working for you.
You can get rid of that warning adding the config `protocol: true` or as an env var `PROTOCOL=true`.
We are going to enforce https through HSTS headers in the future and get rid of this warning.

**Comment by ZerooCool** [comment]
Can you explain in more detail how to add the protocol, to not have the information message in red.

It's good that it seems possible without too much difficulty, but, I do not see how to do that. Can you still help me understand that?

Can you give the correct syntax, please.

**Comment by franciclo** [comment]
Yes, sorry i mistake, i edited the comment above, what i mean is you have to set [this configuration](http://docs.democracyos.org/configuration.html#-protocol-) to `https` but is intended to warn against the lack of SSL. You could add SSL with a reverse proxy and Lets Encrypt, but how to implement that is not a DemocracyOS concern really.

**Comment by ZerooCool** [comment]
Hello.
I changed http to https in the configuration file.

/ Usr / src
nano config / defaults.json

  "protocol": "http",
by
  "protocol": "https",

it is obviously not enough. The error message regarding https is always displayed.
I have to install a certificate on the server?

I also tested to create a user account. The email is not received.
I surely times also install a mail server?

Can you give a track, or a link to help move in this direction?
Thank you.

**Comment by franciclo** [comment]
Hi, you shouldn't change the files in the container, so to add configuration variables you should use enviroment variables.
For development local deployment you could use the `docker-compose.yml` file provided in the repository, so after you cloned the project and open it in a terminal you can start the deployment with `docker-compose up` (this will trigger the build process the first time) and it will start the `app` container and your `mongo` container, you could also create a `docker-compose.override.yml` file where you can put your configuration variables, like you mailer keys from your [mailing provider](http://nodemailer.com/smtp/well-known/), for example:
```
version: '3'

services:
  app:
    environment:
      - DEBUG=democracyos*
      - JWT_SECRET=xxxxxxxxxxxxxx
      - LOCALE=es
      - ORGANIZATION_NAME="DemocracyOS Dev"
      - STAFF=francisco@democracyos.io
      - MONGO_URL=mongodb://mongo/DemocracyOS-dev

      # configure your mailing provider (Mailgun in this case)
      - NOTIFICATIONS_NODEMAILER={"host":"smtp.mailgun.org","port":465,"secure":true,"auth":{"user":"MAILGUN_USER@mg.yourdomain.com","pass":"MAILGUN_PASSWORD"}}

  mongo:
    image: mongo:3.2
    volumes:
      # to persist the data
      - ~/data:/data/db

```

In a small scale production enviroment you should set the production mode on node, and hide the ssl warning. You should also add SSL and a load balancer, your `docker-compose.override.yml` should look something like:

```
version: '3'

services:
  app:
    environment:
      - DEBUG=democracyos*
      - JWT_SECRET=xxxxxxxxxxxxxx
      - LOCALE=es
      - ORGANIZATION_NAME="DemocracyOS Dev"
      - STAFF=francisco@democracyos.io
      - MONGO_URL=mongodb://mongo/DemocracyOS-dev
      - NOTIFICATIONS_NODEMAILER={"host":"smtp.mailgun.org","port":465,"secure":true,"auth":{"user":"MAILGUN_USER@mg.yourdomain.com","pass":"MAILGUN_PASSWORD"}}
      
      # set production mode
      - NODE_ENV=production

      # to remove the ssl warning
      - PROTOCOL=https
      - HTTPS_REDIRECT=no-redirect

  mongo:
    image: mongo:3.2
    volumes:
      # to persist the data
      - ~/data:/data/db

  # Add haproxy load balancer and Lets Encrypt SSL service
  lb:
    image: 'mjlescano/letsencrypt-dockercloud-haproxy:haproxy'
    ...

  letsencrypt:
    image: 'mjlescano/letsencrypt-dockercloud-haproxy:letsencrypt'
    ...
```

**Comment by ZerooCool** [comment]
I closed this request. Thank you.
https://www.visionduweb.eu/wiki/index.php?title=Installer_DemocracyOS#Installer_DemocracyOS_avec_Docker

**Comment by nicostefa** [comment]
> I have the same problem but I'm using a mongo docker instance : in config/defaults.json mongoUrl witch has a value of mongodb://localhost/... should be mongodb://mongo/... so it could connect to an external mongo instance.

I try this way, but it doesn't work.. any solutions?

**Comment by ZerooCool** [comment]
Look my tutorial, i can't make more.
The link is now update.
