### ISSUE TITLE
Public instance

### ISSUE THREAD

**Issue by koulaxizis** [DemocracyOS/democracyos#1488]
Hello! :)

How can I configure my democracyos installation to act like a public instance, as on https://app.democracyos.org/ ?

Thanks in advance for your time!

**Comment by franciclo** [comment]
Hi!
you have to add the `multiForum` config set to `true`.
More info [here](http://docs.democracyos.org/configuration.html#-multiforum-)

**Comment by koulaxizis** [comment]
Thanks mate! :)
