### ISSUE TITLE
HomeForum not loading

### ISSUE THREAD

**Issue by mbiondo** [DemocracyOS/democracyos#1489]
Uncaught (in promise) TypeError: Cannot read property 'count' of undefined     at exports.default (site.js:2178)

**Comment by vaspervnp** [comment]
Same here.

**Comment by franciclo** [comment]
I think this was fixed after 15f7f6e75ef7720335cff22a5b99b61e10bfd1c2 can you please confirm?

**Comment by vaspervnp** [comment]
It is fixed.

**Comment by franciclo** [comment]
Great, thank you!
