### ISSUE TITLE
[v3] User login

### ISSUE THREAD

**Issue by franciclo** [DemocracyOS/democracyos#1495]
Add magic link login.
Test it using cypress.

**Comment by guillecro** [comment]
Checked it!
I actually dont know if the "Continue" button should redirect you to the `/admin` or to the `/`
Thou nothing bad, I like the flow.

I tried by setting a end parameter `DEMOCRACYOS_ADMIN_EMAIL` but i dont see the difference in the flow.

Some "bugs" to look:
- Step 1 says _1/1 User register_ when it should say _1/2 User register_
 - If I close `/init-settings` and i go to `/` it takes me to the limbo but actually it should take me to `/init-settings` if settings are not initialized.. Mhh.. like.. the app is still in a "setup" state.. whatcha think about this?
