### ISSUE TITLE
[V3] Run as a service with SSL

### ISSUE THREAD

**Issue by vaspervnp** [DemocracyOS/democracyos#1532]
I can't seem to find an example of running DemocracyOS on a production environment as a service. Can you post a democracyos.service sample with and without SSL support?

**Comment by vaspervnp** [comment]
Never mind. This worked:
https://github.com/DemocracyOS/democracyos/wiki/Running-as-a-service-on-Ubuntu-12.04

It should be added to the installation documentation.

**Comment by franciclo** [comment]
ssl should be manage from outside the app.
We are using docker for production deploys with haproxy and lets encrypt containers.
Please don't use the [v3] prefix.

**Comment by vaspervnp** [comment]
Thanks.

**Comment by ZerooCool** [comment]
Can you help, with a link, how to install Let's Encrypt, or, haproxy ?
I change the protocol for https but i don't have certificat SSL.

I have a warning : https://www.visionduweb.eu/wiki/index.php?title=Installer_DemocracyOS#Acc.C3.A9der_.C3.A0_DemocracyOS

/usr/src
nano config/defaults.json

{
 "locale": "en",
 "protocol": "http",

by  "protocol": "https",
