### ISSUE TITLE
Crash when going to Manage ->Tags Moderation

### ISSUE THREAD

**Issue by vaspervnp** [DemocracyOS/democracyos#1533]
I have installed and run a service on https://democracy.sonsofpiracy.org. 
However, when I go to Manage ->Tags Moderation the service crashes and must be restarted to continue work.

**Comment by franciclo** [comment]
Hi, can you show see any logs related to the crash?
Also i change the title of the issue because we are using [v3] prefix for version 3 issues only

**Comment by franciclo** [comment]
I was able to reproduce it and now working in a solution.
Thank you for reporting it!

**Comment by franciclo** [comment]
fixed on 2.10.2

**Comment by vaspervnp** [comment]
Excellent. Thank you.
