### ISSUE TITLE
Admin module error?

### ISSUE THREAD

**Issue by vaspervnp** [DemocracyOS/democracyos#1536]
I can't seem to get into the admin module. I have connected as a staff user, but all I get are redirections between admin and 404. The requests seems to be directed at a forum:
https://democracy.sonsofpiracy.org/api/forum?name=admin

**Comment by franciclo** [comment]
Im not able to reproduce this.
Can you explain what steps are you making and if possible some logs from the server related to this issue?

**Comment by vaspervnp** [comment]
I just call this: https://democracy.sonsofpiracy.org/admin when logged in as a staff user. I don't see any errors in the logs. 

In Chrome -> Developer Tools -> Network Tab, is see that I am redirected as if I asked for a forum. 
https://democracy.sonsofpiracy.org/api/forum?name=admin

In the access logs of my Apache Server I see this:

62.***.**.*** - - [12/Mar/2018:11:50:09 +0100] "GET /admin HTTP/1.1" 200 8346 "https://democracy.sonsofpiracy.org/admin" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
62.***.**.** - - [12/Mar/2018:11:50:09 +0100] "GET /lib/simple-line-icons/Simple-Line-Icons.woff2?v=2.4.0 HTTP/1.1" 304 235 "https://democracy.sonsofpiracy.org/site.css" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
62.***.**.** - - [12/Mar/2018:11:50:09 +0100] "GET /site.css HTTP/1.1" 200 49601 "https://democracy.sonsofpiracy.org/admin" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
62.***.**.** - - [12/Mar/2018:11:50:09 +0100] "GET /bootstrap.min.css.map HTTP/1.1" 200 8193 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
62.***.**.**224 - - [12/Mar/2018:11:50:09 +0100] "GET /site.js HTTP/1.1" 200 535697 "https://democracy.sonsofpiracy.org/admin" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
62.***.**.** - - [12/Mar/2018:11:50:10 +0100] "GET /api/user/me?random=0.707683536468716 HTTP/1.1" 200 654 "https://democracy.sonsofpiracy.org/admin" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
62.***.**.** - - [12/Mar/2018:11:50:10 +0100] "GET /lib/boot/logo.png HTTP/1.1" 304 235 "https://democracy.sonsofpiracy.org/admin" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
62.***.**.** - - [12/Mar/2018:11:50:10 +0100] "GET /lib/boot/logo-mobile.png HTTP/1.1" 304 235 "https://democracy.sonsofpiracy.org/admin" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
62.***.**.** - - [12/Mar/2018:11:50:10 +0100] "GET /api/forum?name=admin&random=0.6520704715670358 HTTP/1.1" 404 212 "https://democracy.sonsofpiracy.org/admin" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"


I tried loging possible node errors using this:
/usr/bin/node /home/democracy/public_html/index.js > /tmp/democracy.log 2> democracy.err.log
but I got nothing.


Perhaps I am missing some setting eg in  an .htaccess file? What  am I supposed to see when calling /admin? It is not clear in the documentation.

**Comment by franciclo** [comment]
It seems you are using `MULTI_FORUM=true` this provides a way to host many forums.
To access the admin panel you should click your avatar, then click "My communities" you will be redirected to settings in the forums section, click on the cog icon to enter the admin of the forum you want.

**Comment by vaspervnp** [comment]
Thanks. So there is no way do administer users in a central way as a staff member?

**Comment by franciclo** [comment]
No, they are supposed to be separate forums.
So forum owners or administrators have access to forums, not even staff members.
