### ISSUE TITLE
Default user right

### ISSUE THREAD

**Issue by dlyr** [DemocracyOS/democracyos#1545]
Hi,
I have a locally installed DemocracyOs.
I want to create a community where everyone is author by default:
any registered user should participate, create and edit topics, but not publish them (because I want to moderate topics)
For now I have set my community as Open for All and manually add users to set their right to 
Authors (btw I do not see any listing of registered participant, I have to fill the first letter of their name ...)
Author can create and edit topics but not publish them, nor edit published ones.
But ideally I want to automate this process. I do not find any way to do this, 
is this possible ? 

thanks in advance

**Comment by franciclo** [comment]
This is not possible, sorry.
We are not fixing this big usability problems because we are working on a big redesign (v3), many of this issues will be resolved in the future.

**Comment by dlyr** [comment]
Thank for your replies, keep watching for the new release !
