### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by Sophivorus** [DemocracyOS/democracyos#1554]
I'd like to share an idea which made me think of you.

![screen shot 2018-03-19 at 9 08 02 pm](https://user-images.githubusercontent.com/3542266/37628764-af676550-2bb9-11e8-8716-f3ca612a008f.png)

I'm not sure how far you've gone in the gamification path, but I think it's a good path to push.

**Comment by franciclo** [comment]
Hey! thanks for thinking of us!
Definitely StackExchange is a great case for gamification, we have talk about it.
What is great about it is that it has an important purpose that is to give the community the ability to self organize, the achievements in StackExchange put the user in a position of authority over the content, so they can decide whether a question is a duplicate or badly formulated or an answer is better than another. It also could create, and it does, [authoritarianism](https://www.embeddedrelated.com/showarticle/741.php).
I think it would be wise to provide gamification features when the needs for it appear (like vote delegation, comment moderation, comment tagging), there are nothing worst that useless gamification.
Thanks for bringing this up, i will keep this open for a while if somebody else likes to comment.

**Comment by franciclo** [comment]
Closing this, is a nice topic to discuss though.
Hope to hear more from you in the future Fede! Abrazo!
