### ISSUE TITLE
[v3] Reactions Card for post: Vote & show results

### ISSUE THREAD

**Issue by guillecro** [DemocracyOS/democracyos#1555]
Things to have in mind.
- Depending on the type, we have to respect the configuration (For example, limits)
- Should show a graph or a count of the votes, depending of the reaction type

**Comment by guillecro** [comment]
Hey everyone! I am here with another update on reactions.
This time i would like some feedbacks of my branch `add/vote-reaction`
[![Screenshot_from_2018-03-30_10-49-23.png](https://s14.postimg.org/hzf2302xd/Screenshot_from_2018-03-30_10-49-23.png)](https://postimg.org/image/zcpchuy8d/)

So basically now you can vote the reactions instances of a post.
The way you do it is by creating reaction instances and assigning a content + a rule
Then go to the post and try voting.
Some features:
- You can opt-out from a reaction instance (You can delete your vote.. but actually, the vote is marked as "deleted" so we can track how many times you've votes).
- You can vote as many times as you want as long as you respect the limits of the rule.
- Opt-out your vote from a reaction instance doesnt count as a "vote". It just flags your vote as "deleted".

There is still a lot of work to do and a few fixes but everything seems to be working "right" for some feedbacks.
@florlafuente @franciclo @luarar

**Comment by florlafuente** [comment]
Bravo! Great work @guillecro 
The only thing I've noticed is that Result component shows the total of likes and not the quantity of users who voted. For example, if I vote and then reload the page and vote again, it shows "2 users have participated".

**Comment by guillecro** [comment]
Gotcha. I will give it a look naow!
