### ISSUE TITLE
Image missing while verifying email

### ISSUE THREAD

**Issue by lisandropodesta** [DemocracyOS/democracyos#1601]
I've just registered on the platform and when I went to the link confirming my email addess nothing said that it was confirmed, maybe a missing image was intended to do that. I've used Chrome on Windows 10. Attached a screenshot.

![image](https://user-images.githubusercontent.com/4840520/41257715-7e80d4a0-6d93-11e8-9034-44401ade2dd8.png)

**Comment by franciclo** [comment]
That is not DemocracyOS sorry, is sovereign from Democracy Earth

**Comment by lisandropodesta** [comment]
sorry and thank you!
