### ISSUE TITLE
Server requirements

### ISSUE THREAD

**Issue by petrk94** [DemocracyOS/democracyos#1621]
Hello,

I would like to run DemocracyOS on a shared host server.
What does it need to run it? 
How much RAM is necessary?

Thanks

**Comment by ZerooCool** [comment]
Start with DemocracyOS :
MongoDB
NodeJS & NPM
Git
Make
OpenSSL

 How much RAM is necessary?
I don't no but you can monitoring your system with a little server.
I can use DemocracyOS with Docker and a VPS.

I have create a tutorial for Docker and DemocracyOS, non official, in french :
https://www.visionduweb.eu/wiki/index.php?title=Installer_DemocracyOS#Installer_DemocracyOS_avec_Docker

[RESOLVED]

**Comment by petrk94** [comment]
@ZerooCool in english where a good idea ;) 
I will try to follow this as far I get it translated.
