### ISSUE TITLE
How to change the translation of the registration email?

### ISSUE THREAD

**Issue by ZerooCool** [DemocracyOS/democracyos#1647]
Bonjour, j'aimerais corriger les fautes de langue, pour le message envoyé lors de l'inscription.
Comment modifier les informations de ce texte ?

Hello, I would like to correct the mistakes of language, for the message sent during the registration.
How to modify the information of this text?

Salut, "Utilisateur",

Cliquez s' il vous plaît sur ici pour valider votre adresse de courriel.

L' équipe de DemocracyOS.

Si vous n' avez pas creé un compte sur DemocracyOS, ignorez s' il vous plaît ce courriel.

**Comment by bekirdag** [comment]
This one is coming from a different package, so you should go to https://github.com/DemocracyOS/notifier and create a pull request there with the fixed text

**Comment by ZerooCool** [comment]
Ok, top, thank you.
