### ISSUE TITLE
NEW FEATTURE : Edit a democraty description once created

### ISSUE THREAD

**Issue by VinceLB** [DemocracyOS/democracyos#1649]
- Using firefox browser v63.0.3
- Democraty record created, named "vivrelademocratie"
- In admin menu/democraties
- Democraty "setting button" displays the menu "https://app.democracyos.org/vivrelademocratie/admin/topics"

The new feature would be to allow rights to admins to edit the democraty description.

Thanks

**Comment by franciclo** [comment]
This is possible in latest versión.
In the administrator section in the lateral menu clicking in "Edit forum" you will find the form to make changes in the forum.
