### ISSUE TITLE
Add SEO support

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#360]
Laws or bills listed in a DemocracyOS installment should show in search results whenever someone's googling for related stuff.

1. Add `sitemap.xml`
2. Check [prerender.io](http://prerender.io.) (although it might not be necessary since [this is happening](http://googlewebmastercentral.blogspot.no/2014/05/understanding-web-pages-better.html))
3. Add 404 y 301 (related to #86 )
4. canonical urls
5. Add `robots.txt`

More on all this [here](https://github.com/ekalinin/sitemap.js)

**Comment by gvilarino** [comment]
I think we should reconsider this. Maybe not consider it a blocker, but we definetely should do something to provide SEO-friendly URLs and meta-tags.

**Comment by mjlescano** [comment]
Totally agree with @gvilarino, 

More things to consider:
* Facebook's [open graph protocol](http://ogp.me/) for sharing it on fb and several other platforms.
* [Twitter Cards](https://dev.twitter.com/cards/overview) for twitter.
* [schema.org](http://schema.org/) for search engines scraping:
  + [Organization](http://schema.org/Organization) tags for forums.
  + [Person](http://schema.org/Person) tags for user profiles.
  + [Article](https://schema.org/Article) tags for topics.

**Comment by gvilarino** [comment]
:+1: to adopting widespread, open standards.

Also, I would drop Google Plus as a sharing button
