### ISSUE TITLE
Notify citizens on argument up/downvoting

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#380]
Whenever `citizen`s' arguments are upvoted or downvoted, they should be notified

**Comment by jfresco** [comment]
See #1126. Should we add an e-mail notification?

**Comment by gvilarino** [comment]
I don't think email notifications are required for this. Also, any new email notification should include an option to disable it in settings.

I guess there should also be a new issue about adding a link to all email templates for unsubscribing  that takes you to your settings page.

**Comment by jfresco** [comment]
Agreed; we'll continue with this in #1164. Closing.
