### ISSUE TITLE
After law close. Show up difference btw citizens and legislators

### ISSUE THREAD

**Issue by vmariano** [DemocracyOS/democracyos#435]
In contrast to the opinion between citizens and politicians. When a Law close, we can show up information about the difference between the decision  of the citizen and the politicians. (And the difference).  As idea something like the iconography [1] . 
[1] http://www.lanacion.com.ar/1728238-como-voto-cada-diputado-la-polemica-reforma-de-la-ley-de-abastecimiento

**Comment by slifszyc** [comment]
Any information after the closing date can be added by the forum admin in the `topic`'s `finalMessage` when we decide to include that feature the app
