### ISSUE TITLE
Unify responsive and non-responsive styles into single stylesheets

### ISSUE THREAD

**Issue by vmariano** [DemocracyOS/democracyos#485]
Currently we are writing media queries in separate templates like [boot](https://github.com/DemocracyOS/app/blob/development/lib/boot/boot.styl) and [boot-responsive](https://github.com/DemocracyOS/app/blob/development/lib/boot/boot-responsive.styl) (same thing with settings)

What is the best way to write responsive css?

In my opinion, I think have 2 files for `responsive` and `non-responsive` is a little overhead of maintenance.

Suggestions? better way to unify criteria?

**Comment by jfresco** [comment]
IMO we do not have to distinguish between "responsive styles" and "non-responsive" styles. The _1 `.jade` and 1 `.style` per view_ approach is the proper.
The system wide styles or the styles that affects more than a view should be placed in `lib/boot`.

**Comment by gvilarino** [comment]
Under `/settings`: we have 3 separate `styl` files; we should have just one. The pattern for all components should be:
* One main entry point `.js` file (i.e.: the 'view')
* One single `.jade` template 
* One single `.styl` stylesheet.

Sometimes with complex components (e.g.: `sidebar`) this isn't completely appropriate/comfortable, but at least we shouldn't separate stylesheets into separate files for things like responsiveness. This means `settings-responsive.styl` shouldn't exist.

**Comment by jfresco** [comment]
- [ ] *boot*: has a `boot.styl` and a `boot-responsive.styl`; should be merged.
- [ ] *help*: has a `help.styl` and a `help-responsive.styl`; should be merged.
- [ ] *settings*: has a `settings-heading.styl`,  a `settings-responsive.styl` and `settings-sidebar.styl`; the `-responsive` should be deleted and its contents moved to the other two.

**Comment by gvilarino** [comment]
:+1:
