### ISSUE TITLE
Participants aren't updated when removing arguments/replies

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#513]
Repro:
1. Have two users you can log in as (A and B)
2. Go to clean `law` (with no participants) logged as user A
3. Create an argument
4. Log in with user B
5. Reply to argument created in 2.
6. You should have 2 participants (A & B)
7. Log in with user A and delete argument created in 2.
8. You'll still have 2 participants, even after refresh.

_PLEASE NOTE_: this doesn't mean "always remove participant when their argumets/replies are removed". Participant should be removed only if no other arguments/replies by that user is left and only if they didn't cast a vote.

**Comment by jfresco** [comment]
I think that validate and eventually delete a participant on the [`DELETE /api/comment/:id` endpoint](https://github.com/DemocracyOS/app/blob/development/lib/comment/index.js#L195) would be enough.
Now, participants counter is not being updated when user submits a comment; it can only be seen after refreshing the page.
With little effort we can ensure the same behaviour when user deletes a comment. Afterwards, we can improve the view to update the participants when user submits or deletes a comment.

**Comment by gvilarino** [comment]
@jfresco but deleting a comment may not imply deleting a participant if that user has voted or has more comments/replies than the one being deleted. It's not a trivial thing to do, I think.

**Comment by jfresco** [comment]
I know, I'm not saying to _always_ delete the participant. I'm saying that
the task has to be performed in just one place (or maybe I'm losing
something?).

**Comment by gvilarino** [comment]
Agree with that

**Comment by slifszyc** [comment]
Maybe `participants` should be a calculated (aggregated) attribute merging both ids of users that have commented and voted? I think that'd be a better approach

**Comment by franciclo** [comment]
`participants` have been removes in favor of `boxCount` that represent the number of voters.
Comments participants will be handled separatedly
