### ISSUE TITLE
Cannot able to compile DemocracyOS

### ISSUE THREAD

**Issue by IvanHGuevara** [DemocracyOS/democracyos#514]
Hi guys, how are you?

I'm having some troubles trying to compile my forked DemocracyOS and i really don't know what to do... Probably there's a stupid solution, but i'm not able to find it.

This is my forked repo: https://github.com/LaUES-UTNBA/app

1) I fetched the latest changes you made
2) Rebase my repo with your changes (master)
3) Run "make"

And i get something like the following:

aivan-Studio-1558 (master)$ make
Installing dependencies...
npm WARN package.json co-prompt@1.0.0 No repository field.
npm WARN package.json type-component@0.0.1 No repository field.

> DemocracyOS@0.8.26 postinstall /home/aivan/projects/democracyOSutn
> node ./bin/dos-install && node ./bin/dos-config && node ./bin/dos-build

   installed : code42day/dataset@0.2.2 in 717ms
   installed : component/delegate@0.1.0 in 731ms
   installed : component/type@1.0.0 in 724ms
   installed : code42day/load@1.0.0 in 717ms
   installed : component/event@0.1.0 in 724ms
   installed : component/domify@1.0.0 in 699ms
   installed : component/classes@1.1.2 in 700ms
   installed : component/sort@0.0.3 in 704ms
   installed : component/css@0.0.2 in 728ms
   installed : component/value@1.1.0 in 723ms
   installed : component/query@0.0.1 in 709ms
   installed : component/dropdown@7207a in 1439ms
   installed : component/inserted@0.0.2 in 2095ms
   installed : gvilarino/datepicker@1.0.2 in 961ms
   installed : component/indexof@0.0.1 in 296ms
   installed : component/removed@0.0.3 in 1233ms
  outdated name of a dependency : please update: "andrewrk/diacritics" -> "andrewrk/node-diacritics"
   installed : gvilarino/timepicker@1.1.2a in 1884ms
   installed : jakiestfu/snap.js@8538051df8e2c82a39d2603b6dfd8219ce8f04e6 in 828ms
   installed : cristiandouce/confirmation@d0861 in 1735ms
   installed : component/scroll-to@0.0.1 in 729ms
   installed : andrewrk/diacritics@1.1.0 in 716ms
   installed : chjj/marked@v0.3.2 in 757ms
   installed : cristiandouce/merge-util@0.2.0 in 727ms
   installed : yields/unserialize@0.0.1 in 723ms
   installed : kewah/mixin@0.1.0 in 855ms
   installed : component/delegate@0.2.3 in 217ms
   installed : visionmedia/debug@1.0.3 in 962ms
   installed : component/event@0.1.4 in 298ms
   installed : component/domify@1.3.1 in 236ms
   installed : component/classes@1.2.1 in 785ms
   installed : component/trim@0.0.1 in 1330ms
   installed : component/matches-selector@0.1.4 in 1827ms
   installed : yields/traverse@0.1.1 in 843ms
   installed : yields/isarray@1.0.0 in 276ms
   installed : component/matches-selector@0.1.5 in 361ms
   installed : matthewp/keys@0.0.3 in 360ms
   installed : component/each@0.2.5 in 206ms
   installed : component/type@c817c in 704ms
   installed : matthewp/text@0.0.2 in 354ms
   installed : component/domify@1.3.0 in 299ms
   installed : slifszyc/line-height@0.1.3 in 310ms
   installed : timoxley/offset@1.0.2 in 205ms
   installed : component/spinner@0.1.0 in 761ms
   installed : component/css@0.0.6 in 6076ms
   installed : democracyos/side-comments@0.0.11 in 4721ms
  outdated name of a dependency : please update: "component/get-document" -> "webmodules/get-document"

```
   error : timeout of 5000ms exceeded for "https://raw.githubusercontent.com/component/query/0.0.3/index.js"
```

npm ERR! DemocracyOS@0.8.26 postinstall: `node ./bin/dos-install && node ./bin/dos-config && node ./bin/dos-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DemocracyOS@0.8.26 postinstall script.
npm ERR! This is most likely a problem with the DemocracyOS package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/dos-install && node ./bin/dos-config && node ./bin/dos-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls DemocracyOS
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/home/aivan/.nvm/v0.10.24/bin/node" "/home/aivan/.nvm/v0.10.24/bin/npm" "install"
npm ERR! cwd /home/aivan/projects/democracyOSutn
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/aivan/projects/democracyOSutn/npm-debug.log
npm ERR! not ok code 0
make: **\* [packages] Error 1
aivan-Studio-1558 (master)$ 

I really don't know why "https://raw.githubusercontent.com/component/query/0.0.3/index.js" gets a timeout.... It's clearly up....

Any idea for what i could probably doing wrong?

I'm developing under Ubuntu 14.04.1 LTS

Thanks in advance,

Iván

**Comment by dalareo** [comment]
Same to me. I tried more than 10 times but always the same error.
npm ERR! Failed at the DemocracyOS@0.9.0 postinstall script.
npm ERR! This is most likely a problem with the DemocracyOS package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/dos-install && node ./bin/dos-config && node ./bin/dos-build

**Comment by AivanGuevara** [comment]
David, how you doing?

1) You should ask this kind of stuff at:
https://groups.google.com/forum/#!forum/democracyos-app
2) Sometimes after several times trying, DemocracyOS gets built

Cheers

**Comment by dalareo** [comment]
I was able to do it creating .netrc file with my Github API credentials at ~/.netrc. It was API request limit

**Comment by vmariano** [comment]
If you are runing Linux-based system, sometimes you get 

```
error : timeout of 5000ms exceeded for "https://api.github.com/repos/component/<something>"
```
Looks like a component 1.0.0 bug, with the github api. Run  `component install` in the root of the application. If it fails, try again.
