### ISSUE TITLE
Improve error handling and logging

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#531]
We must find a better way to log and handle errors; especially on the backend.

We're currently using `debug` and we just log stuff, but it might be cool to have some stuff shown through logged to `stderr`, and to be shown differently (i.e.: more visibly) when something goes wrong. `debug` supports that (in a way) but you need to set that up whenever you require it.

I think we could wrap `debug` under a `log` util and provide a more comfortable api.

Another approach would be to mimic [what notifier does](https://github.com/DemocracyOS/notifier/blob/development/source/utils/logger.js), even if we don't make it rely on `logentries`.

Actually this could be a good thing to make into a module/component under DemocracyOS and have all our repos use that.

Thoughts?

**Comment by jfresco** [comment]
You mean to build a wrapper of `debug` in order to have several verbosity levels? (i.e., `error` and `debug`). It could be nice.

I used [Minilog](https://github.com/mixu/minilog) a couple of times and liked the API and flexibility. Supports several verbosity levels and output streams. Works on browsers and server-side, but have no Component support.

**Comment by alejandro-uliski** [comment]
Hey guys, I added a question to gtter, I think here is a good place to add the same question cause the log in this case is not informative:

I am trying to install DemocracyOS on my ubuntu, I get the following error while running make: error : "no remote found for dependency "component/dropdown@7207a". run component open troubleshooting for help." any idea?

**Comment by gvilarino** [comment]
@alejandro-uliski that's just an error with the build in your environment; nothing to do with `DemocracyOS` and thus not on our scope.

**Comment by slifszyc** [comment]
@alejandro-uliski please refer to [this link](https://github.com/DemocracyOS/app/wiki/Installation#random-error-downloading-components) on our wiki

**Comment by mjlescano** [comment]
@gvilarino I did this wrapper for another project:
```javascript
import debug from 'debug'

let base = 'democracyos'

let logLevels = [
  'critical',
  'error',
  'warn',
  'info',
  'debug',
]

let logLevel = logLevels.indexOf(process.env.DEBUG)

if (logLevel > -1) {
  let scope = logLevels.slice(0, logLevel).join(',')
  debug.enable(`${base}:${scope}`)
} else if (process.env.DEBUG === '*') {
  debug.enable(`${base}:*`)
} else {
  debug.enable(process.env.DEBUG)
}

class Log {
  constructor (scope) {
    logLevels.forEach(level => {
      level = `${base}:${level}`
      if (scope) level += `:${scope}`
      this[level] = debug(level)
    })
  }
}

logLevels.forEach(level => {
  Log[level] = debug(`${base}:${level}`)
})

export default Log
```

The idea is to let you log on different leves (`error`, `warning`, etc). And it can be used directly or scoped. The `DEBUG` variable can be used to configure debug level; e.g.: if you set `DEBUG=warn` will only show `critical,error,warn` levels.

**Direct use example:**
```
import log from 'lib/log'

log.critical('Everything is broken, ahahahahah!')
log.warn('A message that will never be read.')
log.debug('Debugging message')
```
**will print:**
```
democracyos:critical Everything is broken, ahahahahah!
democracyos:warning A message that will never be read.
democracyos:debug Debugging message
```


**Scoped example:**
```
import Log from 'lib/log'

let log = new Log('article:show')

log.critical('Everything is broken in this scope, ahahahahah!')
```
**will print:**
```
democracyos:critical:article:show: "Everything is broken in this scope, ahahahahah!"
```

**Comment by gvilarino** [comment]
@mjlescano that's sort of what I have in mind. I'd like to build it on top of `visionmedia/debug` tho, and with some additional stuff. Let's discuss in person.

**Comment by mjlescano** [comment]
[Here's](https://github.com/tj/log.js) a better lib. We can make it configurable to print to `stdout` and/or `.log` files.
