### ISSUE TITLE
[migrations] - Add migrations scripts

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/democracyos#644]
This will facilitate future automatic migrations.

Let's consider using [Migroose CLI](https://github.com/derickbailey/migroose-cli) for it.

**Comment by slifszyc** [comment]
We can find an example of this in [Let's chat](https://github.com/sdelements/lets-chat/tree/master/migrootions)

**Comment by gvilarino** [comment]
:+1:

**Comment by slifszyc** [comment]
Not now, maybe in `DemocracyOS 2.0`
