### ISSUE TITLE
Don't scroll for fitting new comment/reply input if input is already on-screen.

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#659]
What fixed #555 also broke the experience for non-mobile users. Just go to any topic with some decent level of activity and try to reply to an argument.

Automated scrolling should:
1. Only work if the input + submit/cancel buttons are partially off-screen.
2. Be smooth. Add some easing or something to the auto-scroll.

**Comment by solde9** [comment]
I was looking at [component/scroll-to](https://github.com/component/scroll-to). It seems to do what you described but it uses the `window` as the scrolling element while in DemocracyOS it is the `#browser` section what's need to be scrolled.

**Comment by gvilarino** [comment]
@solde9 I guess you may fork `scroll-to` and make the scrolling element part of an `opts` param, and using `window` as default.

**Comment by mjlescano** [comment]
This is already fixed.
