### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by a0viedo** [DemocracyOS/democracyos#695]
Reading through [CONTRIBUTING.md](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTING.md) I couldn't find any mention to a Code of Conduct of any type. Can you consider adding one? A good starting point is the one from [Rust](https://github.com/rust-lang/rust/wiki/Note-development-policy#conduct)

**Comment by gvilarino** [comment]
:+1: 

Will definitely do this before `1.0.0`. I've been looking at [`IO.js`'s governance model](https://github.com/iojs/io.js/blob/v0.12/CONTRIBUTING.md#governance) for a while but any input is good on this matter.
