### ISSUE TITLE
Custom font for app wide icons usage

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#812]
I think we should have a custom font that is builded from a folder of `.svg`s, using something like http://fontcustom.com

The hierarchy should be something like:
+ **/lib/icons**
  + **/icons**: Folder with the `.svg` files that will be compiled to the font.
  + *preview.html*: preview file as a handy list of the available icons (generated by fontcustom)
  + *icons.css*: the file that will be loaded from the layout (generated by fontcustom)

And every time we want to add an icon to the font we just add the `.svg` file to the `/icons` folder and run `fontcustom compile` or whatever lib we are using.

**Comment by mjlescano** [comment]
Alternative lib https://www.npmjs.com/package/glyphicons-css

**Comment by gvilarino** [comment]
We're already using something of sorts for label icons.

**Comment by mjlescano** [comment]
@gvilarino Yes, but not the best way it could be done. 

Right now we're using vector icons in three ways, and all of them should be one compiled font:
  1. `/lib/flaticons/social.styl` it's a font with social icons.
  2. `/lib/flaticons/solid.styl` it's a font with icons, and we don't use all of them.
  3. `/lib/tag-images` it's a folder of svgs, it's not compiled, so we use directly the `.svg`s by itself.

Thinking on `1.0.0`, we could add all `/lib/*/icons/*.svg` files into one font and stick it to the asset compilation process.

**Comment by jfresco** [comment]
In the case of `tag-images` (3), it is pointless to have that images in `svg` format: as far as I could see, that images doesn't need to be scaled. I think they are used in only two places with two different, fixed sizes. We can convert it to two `png` files per tag and compile it in one spritesheet. We reduce the amount of requests and get rid of the `svg` format that is expensive to calculate for mobile browsers.

**Comment by mjlescano** [comment]
@jfresco, agree about the `tags`. With that approach dont forget the `@2x.png` images for retina displays.

**Comment by gvilarino** [comment]
I don't agree. SVGs provide the flexibility we need in order to display the same thing in different settings/resolutions.
