### ISSUE TITLE
gulp watch: Restart server when server side .js changes

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/democracyos#849]
During `watch` task execution, monitor server side file changes and trigger a server restart if one of them is modified.
This can be accomplished using [`nodemon`](https://github.com/remy/nodemon). Be sure that only server side files are monitored. We don't want server to restart if a client side `.js` changes.

**Comment by mjlescano** [comment]
Just for comparison, this two modules are a little more popular:
* Forever: https://github.com/foreverjs/forever
* PM2: https://github.com/Unitech/pm2
