### ISSUE TITLE
Topic: Rename `summary` field to `body`

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/democracyos#901]
- [x] Rename `summary` field to `body` in all code references and sample data.
- [x] Make a [migration script](https://github.com/DemocracyOS/app/wiki/Migrating-to-1.0) after #576, #869, #870 and #482.

**Comment by slifszyc** [comment]
```
var topics = db.topics.find();
topics.forEach(function(topic) {
  topic.body = topic.summary;
  delete topic.summary;
  db.topics.update({ _id: topic._id }, topic);
});
```
