### ISSUE TITLE
JavaScript Standard Style

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/democracyos#907]
- [x] Stick to the [JavaScript Standard Style](https://github.com/feross/standard)
- [x] Review our linter rules.
- [x] Put [this nice badge](https://github.com/feross/standard#badge) in the `README.md`.
- [x] Update our [Style Guidelines](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTING.md#coding-style).

**Comment by mjlescano** [comment]
Keep in mind that that guide enforces no semicolons, we should update ALL our code to be able to stick to it.

**Comment by mjlescano** [comment]
+1

**Comment by mjlescano** [comment]
We´ll enforce with houndci
