### ISSUE TITLE
Rewrite gulpfile and gulp tasks in ES6

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/democracyos#939]
Now `gulp@3.9.0` supports ES6. We have to bump the gulp version and rename `gulpfile.js` to `gulpfile.babel.js`.

**Comment by gvilarino** [comment]
While I agree to have as much as possible on ES6, I hardly find this to be a priority :)

**Comment by slifszyc** [comment]
http://stephensauceda.com/es6-in-your-gulp-tasks/
