### ISSUE TITLE
All front-end collections should extend from lib/store/store.js

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#945]
- [ ] `/lib/feeds/feeds.js`
- [x] `/lib/tags/tags.js`
- [x] `/lib/topics/topics.js`
- [ ] `/lib/users/users.js`
- [ ] `/lib/whitelists/whitelists.js`
- [x] `lib/forums/forums`

**Comment by slifszyc** [comment]
I wouldn't mind doing this strictly for all collections right now
