### ISSUE TITLE
Error: listen EADDRINUSE :::3000

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/democracyos#951]
On development, when running `gulp bws` and then exiting the process with `control+C` on the terminal I get that error message displayed.

A `node` process keeps running on background:

PID TTY           TIME CMD
1052 ttys000    0:07.28 node index.js

**Comment by jfresco** [comment]
I think the root cause is [the way we are launching the server](https://github.com/DemocracyOS/app/blob/1.0.0/lib/build/serve.js#L20). We have to figure out the way of catch the `ctrl+C` signal and gracefully end the process.
Related: #849.

**Comment by slifszyc** [comment]
IMHO `watch` command should run on another terminal tab, independently

**Comment by jfresco** [comment]
You can do it that way: just run `gulp serve` in one tab and `gulp watch` in other.
IMO, there is not a good reason for not using `watch` in a dev environment, but we support both scenarios.

**Comment by gvilarino** [comment]
Agree with @slifszyc on this one. The `watch` task is something that should be used on a need basis, not as the default behavior

**Comment by jfresco** [comment]
Just to clarify:
- The default `gulp` task [is `build serve`](https://github.com/DemocracyOS/app/blob/1.0.0/lib/build/index.js#L74), not `watch` neither `bws` (short for _build watch serve_).
- You can run `gulp serve` in a tab and `gulp watch` in other one if you want. Or you can run `gulp bws` which runs `serve` and `watch` in the same terminal tab.

**Comment by slifszyc** [comment]
https://www.npmjs.com/package/concurrently

might help

**Comment by mjlescano** [comment]
Still happening?
