### ISSUE TITLE
conditioned YES vote 

### ISSUE THREAD

**Issue by ppKrauss** [DemocracyOS/democracyos#987]
Even when law-projects arrives as finished work, where "back to corrections" is impossible, is important to avoid *"NO vote"*, and express something as *"conditioned YES vote"*, that have a very distinct semantic.

PS: I am commenting with base on the use of [EuVoto fork](http://euvoto.org/), and the behaviour of that community of users. I do not known the whole project here... Perhaps the feature already exists here.

**Comment by gvilarino** [comment]
Our approach is based on how legislative bodies across the world work. I'm not entirely illustrated on this matter but it *was* a big debate when we decided to go this way. That's why we include the `abstention` option; the same way it works in real legislative bodies, an abstention means you either can't decide on a specific `topic` or do not agree on how that `topic` is stated/oriented. Arguments for any perspective can be laid out in the debate section.

**Comment by ppKrauss** [comment]
Hi @gvilarino , thanks the fast reply! ;-)

Do you have some link about this "big debate"?  

About the semantic of  `abstention`  is *not* the same (!).  Example... Imagine a context of technical decisions subject to vote:  

* I know Javascript, so, I can vote about Javascript algorithm. I *vote YES* if I like, or *vote NO* if I not like... If I like so much but I, as an expert, see some bug to correct, I can't vote YES (!), I need to *vote "conditional YES"* and indicate how to correct the bug in my comment.

* I not know medicine, so must to *vote abstention* when the theme is medicine. 

Abstention is to say "I not have time" or "I not know this theme", etc. It is *not  to say "conditioned YES"*. In the EuVoto experience we see "condicional-YES intention" rounded to *NO vote* (not to abstention).

**Comment by gvilarino** [comment]
The debate about this was offline (organisation meeting) and wasn't recorded; no link :disappointed: 

The points you make were (in a similar fashion) present during that time but it took further understanding of [what abstaining means](https://en.wikipedia.org/wiki/Abstention) to support our current approach. We also added side-comments to allow correction suggestions.

Conditional `yea` would also imply conditional `nay` and maybe even conditional `x`. I think it would be interesting to try out, but I don't feel it would make much a of a difference while adding complexity to the UX. Have you seen it elsewhere?

**Comment by ppKrauss** [comment]
> Conditional `yea` would also imply conditional `nay` and maybe even conditional `x`. 

I think not:  say *"YES but need to correct a bug"* make sense, because will be grouped with "NO" votes. (say *"NO but..."* not makes sense).

> I think it would be interesting to try out, 

Yes, need a concrete trial before to say that is a good idea, we can do at the EuVoto-fork...

> but I don't feel it would make much a of a difference while adding complexity to the UX. 

A interface option do a "NO vote" in two steps: 1) click NO; 2) reply if "it can be convert to YES in future with some bug-correction that you commented".
 
> Have you seen it elsewhere?

No, is a conclusion using and talking with another users, and reading the comments.

**Comment by gvilarino** [comment]
> I think not: say "YES but need to correct a bug" make sense, because will be grouped with "NO" votes (say "NO but..." not makes sense).

I agree, buy we should be careful about applying software development logic/customs to a legislative process. It's easy to determine and explain to others what a bug is/causes; usually with legislation/decisions/politics tend to be much more about perspective/ideology than about actual facts. In any case, the decision being made with `DemocracyOS` would be about the exact content being discussed in a specific `topic`.

As a personal note, I think it would make a lot more sense to provide a bottom-up feature that would allow users to 'pull-request' upgrades to a specific `topic` and allow that specific ammend to be discussed as well.

**Comment by ppKrauss** [comment]
Good points... Yes, all here is much culture than software ;-)

In DemocracyOS an interesting approach is that the responsibility for communicate the law-project (by synopsis and youtube) is a legislator responsibility. So, if the legislator do a bad communication,  will be take biased or bad vote. The "first perception" (after read synopsis and see youtube) is important in DemocracyOS, and it orients the perceptions (or not) about "basic-bugs".

I think that, in general, when someone  say "there is a bug", is because he/she is annoying and read the full-text... So is a real bug ;-)

**Example**: see Gabriela's comment at http://euvoto.org/law/552c0c626ba208ca3e58681b
is a typical discourse of a *"Conditional YES"* voter. There are two typical positions (that I am interpreting): someone like Gabriela, that is critique but have an expectation of bug-correction, she would vote *"Conditional YES"*; and someone like Raphael, that see so much bugs, losing all hopes, voting *NO* ;-)

----

PS: about other projects I remembering now some ones, for "public consultation", where people not vote to the whole document, but to each paragraph (as in [Medium texts](https://medium.com/))... In Brazil there are a iniciative, [Legislando](http://legislando.nossascidades.org/), that use this approach.  I think this is another approach, and we only suppose at DemocracyOS's votations that documents arrives revised.
